// Auto-generated by scripts/updateData.js — last update: 2026-06-28
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 1141,
  "multiItemOrders": 930,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 195,
      "pct": 17.09
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 151,
      "pct": 13.23
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 147,
      "pct": 12.88
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 110,
      "pct": 9.64
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 106,
      "pct": 9.29
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 100,
      "pct": 8.76
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 90,
      "pct": 7.89
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 87,
      "pct": 7.62
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 80,
      "pct": 7.01
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 73,
      "pct": 6.4
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 72,
      "pct": 6.31
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 67,
      "pct": 5.87
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 64,
      "pct": 5.61
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 63,
      "pct": 5.52
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 62,
      "pct": 5.43
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 60,
      "pct": 5.26
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 5.08
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 57,
      "pct": 5
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 56,
      "pct": 4.91
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 55,
      "pct": 4.82
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 54,
      "pct": 4.73
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 53,
      "pct": 4.65
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 53,
      "pct": 4.65
    },
    {
      "productA": "Osobný odber",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 53,
      "pct": 4.65
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 51,
      "pct": 4.47
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 48,
      "pct": 4.21
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 48,
      "pct": 4.21
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 47,
      "pct": 4.12
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 47,
      "pct": 4.12
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 47,
      "pct": 4.12
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 46,
      "pct": 4.03
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 46,
      "pct": 4.03
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v arašidovom oleji 115 g",
      "count": 46,
      "pct": 4.03
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 45,
      "pct": 3.94
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 44,
      "pct": 3.86
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 43,
      "pct": 3.77
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 42,
      "pct": 3.68
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 42,
      "pct": 3.68
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 3.68
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 42,
      "pct": 3.68
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 42,
      "pct": 3.68
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 41,
      "pct": 3.59
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 41,
      "pct": 3.59
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 3.59
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 3.59
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.51
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.51
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 40,
      "pct": 3.51
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 39,
      "pct": 3.42
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 39,
      "pct": 3.42
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 38,
      "pct": 3.33
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 37,
      "pct": 3.24
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 37,
      "pct": 3.24
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 37,
      "pct": 3.24
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 37,
      "pct": 3.24
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 36,
      "pct": 3.16
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 36,
      "pct": 3.16
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované vínom Muscadet 115 g",
      "count": 36,
      "pct": 3.16
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Nátierka zo sardiniek s whisky 60 g",
      "count": 36,
      "pct": 3.16
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 36,
      "pct": 3.16
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 35,
      "pct": 3.07
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 35,
      "pct": 3.07
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.07
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 35,
      "pct": 3.07
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 34,
      "pct": 2.98
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky Luzienne 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Makrela vo víne s aromatickým korením 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Sardinky v slnečnicovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 33,
      "pct": 2.89
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 32,
      "pct": 2.8
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 31,
      "pct": 2.72
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 30,
      "pct": 2.63
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 30,
      "pct": 2.63
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 30,
      "pct": 2.63
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 30,
      "pct": 2.63
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 29,
      "pct": 2.54
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s timutským korením 115 g",
      "count": 29,
      "pct": 2.54
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 29,
      "pct": 2.54
    }
  ]
};
