// Auto-generated by scripts/updateData.js — last update: 2026-07-09
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 2165,
  "multiItemOrders": 1784,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 508,
      "pct": 23.46
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 437,
      "pct": 20.18
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 314,
      "pct": 14.5
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 289,
      "pct": 13.35
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 251,
      "pct": 11.59
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 193,
      "pct": 8.91
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 192,
      "pct": 8.87
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 184,
      "pct": 8.5
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 176,
      "pct": 8.13
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 167,
      "pct": 7.71
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 164,
      "pct": 7.58
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 157,
      "pct": 7.25
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 156,
      "pct": 7.21
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 132,
      "pct": 6.1
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 127,
      "pct": 5.87
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 124,
      "pct": 5.73
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 123,
      "pct": 5.68
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 116,
      "pct": 5.36
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 114,
      "pct": 5.27
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 108,
      "pct": 4.99
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 107,
      "pct": 4.94
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 103,
      "pct": 4.76
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 101,
      "pct": 4.67
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 97,
      "pct": 4.48
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 92,
      "pct": 4.25
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 90,
      "pct": 4.16
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 89,
      "pct": 4.11
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 88,
      "pct": 4.06
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 87,
      "pct": 4.02
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 85,
      "pct": 3.93
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 84,
      "pct": 3.88
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 83,
      "pct": 3.83
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 81,
      "pct": 3.74
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 79,
      "pct": 3.65
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 79,
      "pct": 3.65
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 78,
      "pct": 3.6
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 77,
      "pct": 3.56
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 77,
      "pct": 3.56
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák ve vlastní šťávě 207 g",
      "count": 76,
      "pct": 3.51
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 75,
      "pct": 3.46
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 75,
      "pct": 3.46
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 72,
      "pct": 3.33
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 72,
      "pct": 3.33
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 72,
      "pct": 3.33
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 72,
      "pct": 3.33
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 70,
      "pct": 3.23
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 69,
      "pct": 3.19
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 69,
      "pct": 3.19
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 67,
      "pct": 3.09
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 67,
      "pct": 3.09
    },
    {
      "productA": "Makrela s hořčicí 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 66,
      "pct": 3.05
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 65,
      "pct": 3
    },
    {
      "productA": "Salát z makrely s mrkví a čočkou Beluga 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 65,
      "pct": 3
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 63,
      "pct": 2.91
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 63,
      "pct": 2.91
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 63,
      "pct": 2.91
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 63,
      "pct": 2.91
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 62,
      "pct": 2.86
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 61,
      "pct": 2.82
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 61,
      "pct": 2.82
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 61,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s pepřem Batak a kurkumou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 61,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 61,
      "pct": 2.82
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 60,
      "pct": 2.77
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 60,
      "pct": 2.77
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 59,
      "pct": 2.73
    },
    {
      "productA": "Rillettes z tresky se sečuánským pepřem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 58,
      "pct": 2.68
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 58,
      "pct": 2.68
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 57,
      "pct": 2.63
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 57,
      "pct": 2.63
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 56,
      "pct": 2.59
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 55,
      "pct": 2.54
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 55,
      "pct": 2.54
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 55,
      "pct": 2.54
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 54,
      "pct": 2.49
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
      "count": 53,
      "pct": 2.45
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 53,
      "pct": 2.45
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 53,
      "pct": 2.45
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 52,
      "pct": 2.4
    },
    {
      "productA": "Salát z tuňáka s paprikami a černou rýží 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 52,
      "pct": 2.4
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 50,
      "pct": 2.31
    },
    {
      "productA": "Makrela s hořčicí 112,5 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 49,
      "pct": 2.26
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 49,
      "pct": 2.26
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 49,
      "pct": 2.26
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s kandovaným citronem a koriandrem na konzumaci po tepelné úpravě 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 48,
      "pct": 2.22
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji s česnekem 160 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 47,
      "pct": 2.17
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Rillettes z tresky se sečuánským pepřem 60 g",
      "count": 46,
      "pct": 2.12
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 46,
      "pct": 2.12
    }
  ]
};
