// Auto-generated by scripts/updateData.js — last update: 2026-04-12
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 912,
  "multiItemOrders": 756,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 163,
      "pct": 17.87
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 113,
      "pct": 12.39
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 103,
      "pct": 11.29
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 97,
      "pct": 10.64
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 83,
      "pct": 9.1
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 81,
      "pct": 8.88
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 80,
      "pct": 8.77
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 74,
      "pct": 8.11
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 70,
      "pct": 7.68
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 62,
      "pct": 6.8
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 6.36
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 58,
      "pct": 6.36
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 57,
      "pct": 6.25
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 52,
      "pct": 5.7
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 52,
      "pct": 5.7
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 51,
      "pct": 5.59
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 50,
      "pct": 5.48
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 49,
      "pct": 5.37
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 47,
      "pct": 5.15
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 46,
      "pct": 5.04
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 46,
      "pct": 5.04
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 45,
      "pct": 4.93
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 44,
      "pct": 4.82
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 43,
      "pct": 4.71
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 4.61
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 4.61
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 4.5
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 41,
      "pct": 4.5
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 40,
      "pct": 4.39
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v arašidovom oleji 115 g",
      "count": 40,
      "pct": 4.39
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 39,
      "pct": 4.28
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 39,
      "pct": 4.28
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 38,
      "pct": 4.17
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 37,
      "pct": 4.06
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 37,
      "pct": 4.06
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 37,
      "pct": 4.06
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 37,
      "pct": 4.06
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 37,
      "pct": 4.06
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 36,
      "pct": 3.95
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 36,
      "pct": 3.95
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 36,
      "pct": 3.95
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 36,
      "pct": 3.95
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 36,
      "pct": 3.95
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 35,
      "pct": 3.84
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 35,
      "pct": 3.84
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.84
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 34,
      "pct": 3.73
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 33,
      "pct": 3.62
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 32,
      "pct": 3.51
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 32,
      "pct": 3.51
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 31,
      "pct": 3.4
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 31,
      "pct": 3.4
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 31,
      "pct": 3.4
    },
    {
      "productA": "Sardinky v slnečnicovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 31,
      "pct": 3.4
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 31,
      "pct": 3.4
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 30,
      "pct": 3.29
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 30,
      "pct": 3.29
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované vínom Muscadet 115 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Nátierka zo sardiniek s whisky 60 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 29,
      "pct": 3.18
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Makrela vo víne s aromatickým korením 118 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela s paradajkami 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.07
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky Luzienne 115 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Osobný odber",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 27,
      "pct": 2.96
    },
    {
      "productA": "Makrela s paradajkami 112,5 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Tuniak v olivovom oleji s cesnakom 160 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Makrela vo víne s aromatickým korením 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 26,
      "pct": 2.85
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 26,
      "pct": 2.85
    }
  ]
};
