// Auto-generated by scripts/updateData.js — last update: 2026-06-25
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 2056,
  "multiItemOrders": 1696,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 486,
      "pct": 23.64
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 401,
      "pct": 19.5
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 287,
      "pct": 13.96
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 281,
      "pct": 13.67
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 235,
      "pct": 11.43
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 187,
      "pct": 9.1
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 173,
      "pct": 8.41
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 172,
      "pct": 8.37
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 171,
      "pct": 8.32
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 161,
      "pct": 7.83
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 154,
      "pct": 7.49
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 151,
      "pct": 7.34
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 147,
      "pct": 7.15
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 128,
      "pct": 6.23
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 125,
      "pct": 6.08
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 119,
      "pct": 5.79
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 116,
      "pct": 5.64
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 110,
      "pct": 5.35
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 108,
      "pct": 5.25
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 101,
      "pct": 4.91
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 98,
      "pct": 4.77
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 98,
      "pct": 4.77
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 95,
      "pct": 4.62
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 93,
      "pct": 4.52
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 88,
      "pct": 4.28
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 86,
      "pct": 4.18
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 86,
      "pct": 4.18
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 84,
      "pct": 4.09
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 82,
      "pct": 3.99
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 81,
      "pct": 3.94
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 78,
      "pct": 3.79
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 78,
      "pct": 3.79
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 77,
      "pct": 3.75
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 75,
      "pct": 3.65
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 74,
      "pct": 3.6
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 74,
      "pct": 3.6
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 73,
      "pct": 3.55
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 73,
      "pct": 3.55
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 72,
      "pct": 3.5
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 72,
      "pct": 3.5
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 72,
      "pct": 3.5
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 70,
      "pct": 3.4
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák ve vlastní šťávě 207 g",
      "count": 70,
      "pct": 3.4
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 69,
      "pct": 3.36
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 67,
      "pct": 3.26
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 67,
      "pct": 3.26
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 66,
      "pct": 3.21
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 65,
      "pct": 3.16
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 65,
      "pct": 3.16
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 64,
      "pct": 3.11
    },
    {
      "productA": "Salát z makrely s mrkví a čočkou Beluga 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 64,
      "pct": 3.11
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 63,
      "pct": 3.06
    },
    {
      "productA": "Makrela s hořčicí 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 61,
      "pct": 2.97
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 61,
      "pct": 2.97
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 60,
      "pct": 2.92
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 59,
      "pct": 2.87
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Rillettes z tresky se sečuánským pepřem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 58,
      "pct": 2.82
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 57,
      "pct": 2.77
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 56,
      "pct": 2.72
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 56,
      "pct": 2.72
    },
    {
      "productA": "Sardinky s pepřem Batak a kurkumou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 56,
      "pct": 2.72
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 56,
      "pct": 2.72
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 56,
      "pct": 2.72
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 55,
      "pct": 2.68
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 54,
      "pct": 2.63
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 53,
      "pct": 2.58
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 52,
      "pct": 2.53
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 52,
      "pct": 2.53
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 52,
      "pct": 2.53
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 51,
      "pct": 2.48
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 51,
      "pct": 2.48
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 51,
      "pct": 2.48
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
      "count": 50,
      "pct": 2.43
    },
    {
      "productA": "Salát z tuňáka s paprikami a černou rýží 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 50,
      "pct": 2.43
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 49,
      "pct": 2.38
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 49,
      "pct": 2.38
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 48,
      "pct": 2.33
    },
    {
      "productA": "Makrela s hořčicí 112,5 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 47,
      "pct": 2.29
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 47,
      "pct": 2.29
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 47,
      "pct": 2.29
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Rillettes z tresky se sečuánským pepřem 60 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji s česnekem 160 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Pomazánka ze sardinek a whisky 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 46,
      "pct": 2.24
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Sardinky s kandovaným citronem a koriandrem na konzumaci po tepelné úpravě 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Pomazánka ze sardinek a whisky 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 45,
      "pct": 2.19
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 44,
      "pct": 2.14
    }
  ]
};
