// Auto-generated by scripts/updateData.js — last update: 2026-07-04
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 1153,
  "multiItemOrders": 937,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 196,
      "pct": 17
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 154,
      "pct": 13.36
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 148,
      "pct": 12.84
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 110,
      "pct": 9.54
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 107,
      "pct": 9.28
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 101,
      "pct": 8.76
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 91,
      "pct": 7.89
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 87,
      "pct": 7.55
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 80,
      "pct": 6.94
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 73,
      "pct": 6.33
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 72,
      "pct": 6.24
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 68,
      "pct": 5.9
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 65,
      "pct": 5.64
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 63,
      "pct": 5.46
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 62,
      "pct": 5.38
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 62,
      "pct": 5.38
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 5.03
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 57,
      "pct": 4.94
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 57,
      "pct": 4.94
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 56,
      "pct": 4.86
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 54,
      "pct": 4.68
    },
    {
      "productA": "Osobný odber",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 54,
      "pct": 4.68
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 53,
      "pct": 4.6
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 53,
      "pct": 4.6
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 51,
      "pct": 4.42
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 49,
      "pct": 4.25
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 48,
      "pct": 4.16
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 48,
      "pct": 4.16
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 48,
      "pct": 4.16
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 47,
      "pct": 4.08
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 46,
      "pct": 3.99
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 46,
      "pct": 3.99
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v arašidovom oleji 115 g",
      "count": 46,
      "pct": 3.99
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 45,
      "pct": 3.9
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 44,
      "pct": 3.82
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 43,
      "pct": 3.73
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 43,
      "pct": 3.73
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 42,
      "pct": 3.64
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 42,
      "pct": 3.64
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 3.64
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 42,
      "pct": 3.64
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 41,
      "pct": 3.56
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 41,
      "pct": 3.56
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 3.56
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 3.56
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.47
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.47
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 40,
      "pct": 3.47
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 40,
      "pct": 3.47
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 39,
      "pct": 3.38
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 39,
      "pct": 3.38
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 38,
      "pct": 3.3
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 37,
      "pct": 3.21
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 37,
      "pct": 3.21
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Nátierka zo sardiniek s whisky 60 g",
      "count": 37,
      "pct": 3.21
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 37,
      "pct": 3.21
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 36,
      "pct": 3.12
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 36,
      "pct": 3.12
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované vínom Muscadet 115 g",
      "count": 36,
      "pct": 3.12
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 36,
      "pct": 3.12
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Makrela vo víne s aromatickým korením 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 35,
      "pct": 3.04
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 34,
      "pct": 2.95
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky Luzienne 115 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Sardinky v slnečnicovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 33,
      "pct": 2.86
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 32,
      "pct": 2.78
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 31,
      "pct": 2.69
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 31,
      "pct": 2.69
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 31,
      "pct": 2.69
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 31,
      "pct": 2.69
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 31,
      "pct": 2.69
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 30,
      "pct": 2.6
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 30,
      "pct": 2.6
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 30,
      "pct": 2.6
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 29,
      "pct": 2.52
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s timutským korením 115 g",
      "count": 29,
      "pct": 2.52
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 29,
      "pct": 2.52
    }
  ]
};
