// Auto-generated by scripts/updateData.js — last update: 2026-06-20
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 76,
    "totalRevenue": 96.74,
    "totalOrders": 4,
    "avgRevenue": 1.27,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 76,
    "totalRevenue": 75.36,
    "totalOrders": 2,
    "avgRevenue": 0.99,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 76,
    "totalRevenue": 80.32,
    "totalOrders": 1,
    "avgRevenue": 1.06,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 76,
    "totalRevenue": 102.54,
    "totalOrders": 3,
    "avgRevenue": 1.35,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 76,
    "totalRevenue": 268.68,
    "totalOrders": 6,
    "avgRevenue": 3.54,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 76,
    "totalRevenue": 481.65,
    "totalOrders": 8,
    "avgRevenue": 6.34,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 76,
    "totalRevenue": 250.52,
    "totalOrders": 6,
    "avgRevenue": 3.3,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 76,
    "totalRevenue": 519.94,
    "totalOrders": 13,
    "avgRevenue": 6.84,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 76,
    "totalRevenue": 658.14,
    "totalOrders": 10,
    "avgRevenue": 8.66,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 76,
    "totalRevenue": 415.87,
    "totalOrders": 7,
    "avgRevenue": 5.47,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 76,
    "totalRevenue": 780.58,
    "totalOrders": 13,
    "avgRevenue": 10.27,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 76,
    "totalRevenue": 395.5,
    "totalOrders": 6,
    "avgRevenue": 5.2,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 76,
    "totalRevenue": 773.53,
    "totalOrders": 13,
    "avgRevenue": 10.18,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 76,
    "totalRevenue": 369.24,
    "totalOrders": 7,
    "avgRevenue": 4.86,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 76,
    "totalRevenue": 566.93,
    "totalOrders": 8,
    "avgRevenue": 7.46,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 76,
    "totalRevenue": 1104.49,
    "totalOrders": 18,
    "avgRevenue": 14.53,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 76,
    "totalRevenue": 898.17,
    "totalOrders": 16,
    "avgRevenue": 11.82,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 76,
    "totalRevenue": 748.62,
    "totalOrders": 14,
    "avgRevenue": 9.85,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 76,
    "totalRevenue": 778.31,
    "totalOrders": 15,
    "avgRevenue": 10.24,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 76,
    "totalRevenue": 561.9,
    "totalOrders": 8,
    "avgRevenue": 7.39,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 76,
    "totalRevenue": 387.75,
    "totalOrders": 6,
    "avgRevenue": 5.1,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 71,
    "totalRevenue": 223.42,
    "totalOrders": 4,
    "avgRevenue": 3.15,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 71,
    "totalRevenue": 85.24,
    "totalOrders": 2,
    "avgRevenue": 1.2,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 71,
    "totalRevenue": 107.52,
    "totalOrders": 2,
    "avgRevenue": 1.51,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 71,
    "totalRevenue": 181.78,
    "totalOrders": 4,
    "avgRevenue": 2.56,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 71,
    "totalRevenue": 23.8,
    "totalOrders": 1,
    "avgRevenue": 0.34,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 71,
    "totalRevenue": 291.37,
    "totalOrders": 7,
    "avgRevenue": 4.1,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 71,
    "totalRevenue": 798.67,
    "totalOrders": 15,
    "avgRevenue": 11.25,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 71,
    "totalRevenue": 932.8,
    "totalOrders": 16,
    "avgRevenue": 13.14,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 71,
    "totalRevenue": 604.88,
    "totalOrders": 10,
    "avgRevenue": 8.52,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 71,
    "totalRevenue": 289.24,
    "totalOrders": 8,
    "avgRevenue": 4.07,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 71,
    "totalRevenue": 249.21,
    "totalOrders": 7,
    "avgRevenue": 3.51,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 71,
    "totalRevenue": 1173.65,
    "totalOrders": 19,
    "avgRevenue": 16.53,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 71,
    "totalRevenue": 601.48,
    "totalOrders": 10,
    "avgRevenue": 8.47,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 71,
    "totalRevenue": 636.96,
    "totalOrders": 13,
    "avgRevenue": 8.97,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 71,
    "totalRevenue": 860.21,
    "totalOrders": 21,
    "avgRevenue": 12.12,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 71,
    "totalRevenue": 546.71,
    "totalOrders": 10,
    "avgRevenue": 7.7,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 71,
    "totalRevenue": 814.56,
    "totalOrders": 11,
    "avgRevenue": 11.47,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 71,
    "totalRevenue": 1219.92,
    "totalOrders": 21,
    "avgRevenue": 17.18,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 71,
    "totalRevenue": 654.31,
    "totalOrders": 12,
    "avgRevenue": 9.22,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 71,
    "totalRevenue": 191.64,
    "totalOrders": 3,
    "avgRevenue": 2.7,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 76,
    "totalRevenue": 207.27,
    "totalOrders": 2,
    "avgRevenue": 2.73,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 76,
    "totalRevenue": 57.18,
    "totalOrders": 2,
    "avgRevenue": 0.75,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 76,
    "totalRevenue": 71.98,
    "totalOrders": 1,
    "avgRevenue": 0.95,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 76,
    "totalRevenue": 19.06,
    "totalOrders": 1,
    "avgRevenue": 0.25,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 76,
    "totalRevenue": 49.4,
    "totalOrders": 1,
    "avgRevenue": 0.65,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 76,
    "totalRevenue": 136.14,
    "totalOrders": 3,
    "avgRevenue": 1.79,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 76,
    "totalRevenue": 358.18,
    "totalOrders": 7,
    "avgRevenue": 4.71,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 76,
    "totalRevenue": 697.34,
    "totalOrders": 11,
    "avgRevenue": 9.18,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 76,
    "totalRevenue": 675.31,
    "totalOrders": 11,
    "avgRevenue": 8.89,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 76,
    "totalRevenue": 387.15,
    "totalOrders": 10,
    "avgRevenue": 5.09,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 76,
    "totalRevenue": 713.45,
    "totalOrders": 14,
    "avgRevenue": 9.39,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 76,
    "totalRevenue": 752.08,
    "totalOrders": 9,
    "avgRevenue": 9.9,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 76,
    "totalRevenue": 450.63,
    "totalOrders": 11,
    "avgRevenue": 5.93,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 76,
    "totalRevenue": 462.69,
    "totalOrders": 12,
    "avgRevenue": 6.09,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 76,
    "totalRevenue": 842.69,
    "totalOrders": 8,
    "avgRevenue": 11.09,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 76,
    "totalRevenue": 464.86,
    "totalOrders": 7,
    "avgRevenue": 6.12,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 76,
    "totalRevenue": 995.2,
    "totalOrders": 17,
    "avgRevenue": 13.09,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 76,
    "totalRevenue": 1011.23,
    "totalOrders": 18,
    "avgRevenue": 13.31,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 76,
    "totalRevenue": 635.69,
    "totalOrders": 12,
    "avgRevenue": 8.36,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 76,
    "totalRevenue": 853.83,
    "totalOrders": 16,
    "avgRevenue": 11.23,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 76,
    "totalRevenue": 915.38,
    "totalOrders": 13,
    "avgRevenue": 12.04,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 76,
    "totalRevenue": 35.02,
    "totalOrders": 2,
    "avgRevenue": 0.46,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 68,
    "totalRevenue": 138.43,
    "totalOrders": 3,
    "avgRevenue": 2.04,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 68,
    "totalRevenue": 34.76,
    "totalOrders": 1,
    "avgRevenue": 0.51,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 68,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 68,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 68,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 68,
    "totalRevenue": 122.19,
    "totalOrders": 3,
    "avgRevenue": 1.8,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 68,
    "totalRevenue": 78.45,
    "totalOrders": 2,
    "avgRevenue": 1.15,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 68,
    "totalRevenue": 247.97,
    "totalOrders": 6,
    "avgRevenue": 3.65,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 68,
    "totalRevenue": 201.94,
    "totalOrders": 5,
    "avgRevenue": 2.97,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 68,
    "totalRevenue": 528.46,
    "totalOrders": 12,
    "avgRevenue": 7.77,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 68,
    "totalRevenue": 437.07,
    "totalOrders": 10,
    "avgRevenue": 6.43,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 68,
    "totalRevenue": 429.27,
    "totalOrders": 11,
    "avgRevenue": 6.31,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 68,
    "totalRevenue": 319.73,
    "totalOrders": 7,
    "avgRevenue": 4.7,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 68,
    "totalRevenue": 351.75,
    "totalOrders": 9,
    "avgRevenue": 5.17,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 68,
    "totalRevenue": 74.22,
    "totalOrders": 2,
    "avgRevenue": 1.09,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 68,
    "totalRevenue": 273.21,
    "totalOrders": 3,
    "avgRevenue": 4.02,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 68,
    "totalRevenue": 532.02,
    "totalOrders": 9,
    "avgRevenue": 7.82,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 68,
    "totalRevenue": 773.72,
    "totalOrders": 9,
    "avgRevenue": 11.38,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 68,
    "totalRevenue": 410.38,
    "totalOrders": 7,
    "avgRevenue": 6.04,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 68,
    "totalRevenue": 767.85,
    "totalOrders": 17,
    "avgRevenue": 11.29,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 68,
    "totalRevenue": 455.58,
    "totalOrders": 8,
    "avgRevenue": 6.7,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 68,
    "totalRevenue": 495.84,
    "totalOrders": 10,
    "avgRevenue": 7.29,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 68,
    "totalRevenue": 331.5,
    "totalOrders": 8,
    "avgRevenue": 4.88,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 68,
    "totalRevenue": 392.7,
    "totalOrders": 5,
    "avgRevenue": 5.78,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 72,
    "totalRevenue": 22.82,
    "totalOrders": 1,
    "avgRevenue": 0.32,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 72,
    "totalRevenue": 50.26,
    "totalOrders": 2,
    "avgRevenue": 0.7,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 72,
    "totalRevenue": 77.82,
    "totalOrders": 2,
    "avgRevenue": 1.08,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 72,
    "totalRevenue": 25.44,
    "totalOrders": 1,
    "avgRevenue": 0.35,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 72,
    "totalRevenue": 26.41,
    "totalOrders": 1,
    "avgRevenue": 0.37,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 72,
    "totalRevenue": 193.14,
    "totalOrders": 3,
    "avgRevenue": 2.68,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 72,
    "totalRevenue": 134.41,
    "totalOrders": 2,
    "avgRevenue": 1.87,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 72,
    "totalRevenue": 105.97,
    "totalOrders": 2,
    "avgRevenue": 1.47,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 72,
    "totalRevenue": 414.97,
    "totalOrders": 9,
    "avgRevenue": 5.76,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 72,
    "totalRevenue": 727.56,
    "totalOrders": 13,
    "avgRevenue": 10.11,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 72,
    "totalRevenue": 816.18,
    "totalOrders": 11,
    "avgRevenue": 11.34,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 72,
    "totalRevenue": 888.6,
    "totalOrders": 7,
    "avgRevenue": 12.34,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 72,
    "totalRevenue": 357.14,
    "totalOrders": 8,
    "avgRevenue": 4.96,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 72,
    "totalRevenue": 565.37,
    "totalOrders": 9,
    "avgRevenue": 7.85,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 72,
    "totalRevenue": 326.99,
    "totalOrders": 6,
    "avgRevenue": 4.54,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 72,
    "totalRevenue": 358.96,
    "totalOrders": 6,
    "avgRevenue": 4.99,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 72,
    "totalRevenue": 245.13,
    "totalOrders": 5,
    "avgRevenue": 3.4,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 72,
    "totalRevenue": 673.36,
    "totalOrders": 12,
    "avgRevenue": 9.35,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 72,
    "totalRevenue": 319.12,
    "totalOrders": 7,
    "avgRevenue": 4.43,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 72,
    "totalRevenue": 655.05,
    "totalOrders": 12,
    "avgRevenue": 9.1,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 72,
    "totalRevenue": 657.19,
    "totalOrders": 13,
    "avgRevenue": 9.13,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 72,
    "totalRevenue": 239.47,
    "totalOrders": 3,
    "avgRevenue": 3.33,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 72,
    "totalRevenue": 314.46,
    "totalOrders": 3,
    "avgRevenue": 4.37,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 67,
    "totalRevenue": 88.07,
    "totalOrders": 1,
    "avgRevenue": 1.31,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 67,
    "totalRevenue": 70.92,
    "totalOrders": 1,
    "avgRevenue": 1.06,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 67,
    "totalRevenue": 68.93,
    "totalOrders": 1,
    "avgRevenue": 1.03,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 67,
    "totalRevenue": 409.85,
    "totalOrders": 7,
    "avgRevenue": 6.12,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 67,
    "totalRevenue": 220.36,
    "totalOrders": 5,
    "avgRevenue": 3.29,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 67,
    "totalRevenue": 915.92,
    "totalOrders": 14,
    "avgRevenue": 13.67,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 67,
    "totalRevenue": 521.47,
    "totalOrders": 9,
    "avgRevenue": 7.78,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 67,
    "totalRevenue": 235.3,
    "totalOrders": 6,
    "avgRevenue": 3.51,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 67,
    "totalRevenue": 247.83,
    "totalOrders": 9,
    "avgRevenue": 3.7,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 67,
    "totalRevenue": 553.62,
    "totalOrders": 10,
    "avgRevenue": 8.26,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 67,
    "totalRevenue": 388.37,
    "totalOrders": 6,
    "avgRevenue": 5.8,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 67,
    "totalRevenue": 341.46,
    "totalOrders": 7,
    "avgRevenue": 5.1,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 67,
    "totalRevenue": 768.84,
    "totalOrders": 9,
    "avgRevenue": 11.48,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 67,
    "totalRevenue": 545.89,
    "totalOrders": 9,
    "avgRevenue": 8.15,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 67,
    "totalRevenue": 541.32,
    "totalOrders": 9,
    "avgRevenue": 8.08,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 67,
    "totalRevenue": 261.66,
    "totalOrders": 5,
    "avgRevenue": 3.91,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 67,
    "totalRevenue": 236.47,
    "totalOrders": 7,
    "avgRevenue": 3.53,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 67,
    "totalRevenue": 387.58,
    "totalOrders": 10,
    "avgRevenue": 5.78,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 67,
    "totalRevenue": 208.86,
    "totalOrders": 4,
    "avgRevenue": 3.12,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 67,
    "totalRevenue": 463.17,
    "totalOrders": 7,
    "avgRevenue": 6.91,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 62,
    "totalRevenue": 145.7,
    "totalOrders": 3,
    "avgRevenue": 2.35,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 62,
    "totalRevenue": 119.61,
    "totalOrders": 1,
    "avgRevenue": 1.93,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 62,
    "totalRevenue": 68.78,
    "totalOrders": 1,
    "avgRevenue": 1.11,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 62,
    "totalRevenue": 58.88,
    "totalOrders": 2,
    "avgRevenue": 0.95,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 62,
    "totalRevenue": 550.42,
    "totalOrders": 8,
    "avgRevenue": 8.88,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 62,
    "totalRevenue": 338.65,
    "totalOrders": 7,
    "avgRevenue": 5.46,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 62,
    "totalRevenue": 473.4,
    "totalOrders": 8,
    "avgRevenue": 7.64,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 62,
    "totalRevenue": 445.63,
    "totalOrders": 7,
    "avgRevenue": 7.19,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 62,
    "totalRevenue": 471.46,
    "totalOrders": 8,
    "avgRevenue": 7.6,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 62,
    "totalRevenue": 432.77,
    "totalOrders": 7,
    "avgRevenue": 6.98,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 62,
    "totalRevenue": 129.91,
    "totalOrders": 3,
    "avgRevenue": 2.1,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 62,
    "totalRevenue": 185.53,
    "totalOrders": 5,
    "avgRevenue": 2.99,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 62,
    "totalRevenue": 296.11,
    "totalOrders": 6,
    "avgRevenue": 4.78,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 62,
    "totalRevenue": 450.8,
    "totalOrders": 10,
    "avgRevenue": 7.27,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 62,
    "totalRevenue": 623.2,
    "totalOrders": 9,
    "avgRevenue": 10.05,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 62,
    "totalRevenue": 247.55,
    "totalOrders": 8,
    "avgRevenue": 3.99,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 62,
    "totalRevenue": 433.59,
    "totalOrders": 6,
    "avgRevenue": 6.99,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 62,
    "totalRevenue": 630.49,
    "totalOrders": 10,
    "avgRevenue": 10.17,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 62,
    "totalRevenue": 248.32,
    "totalOrders": 6,
    "avgRevenue": 4.01,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 62,
    "totalRevenue": 556.56,
    "totalOrders": 9,
    "avgRevenue": 8.98,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 62,
    "totalRevenue": 108.42,
    "totalOrders": 3,
    "avgRevenue": 1.75,
    "avgOrders": 0.05
  }
];
