// Auto-generated by scripts/updateData.js — last update: 2026-07-21
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 81,
    "totalRevenue": 96.74,
    "totalOrders": 4,
    "avgRevenue": 1.19,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 81,
    "totalRevenue": 128.91,
    "totalOrders": 3,
    "avgRevenue": 1.59,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 81,
    "totalRevenue": 80.32,
    "totalOrders": 1,
    "avgRevenue": 0.99,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 81,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 81,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 81,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 81,
    "totalRevenue": 172.15,
    "totalOrders": 4,
    "avgRevenue": 2.13,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 81,
    "totalRevenue": 268.68,
    "totalOrders": 6,
    "avgRevenue": 3.32,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 81,
    "totalRevenue": 608.94,
    "totalOrders": 11,
    "avgRevenue": 7.52,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 81,
    "totalRevenue": 250.52,
    "totalOrders": 6,
    "avgRevenue": 3.09,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 81,
    "totalRevenue": 519.94,
    "totalOrders": 13,
    "avgRevenue": 6.42,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 81,
    "totalRevenue": 800.06,
    "totalOrders": 12,
    "avgRevenue": 9.88,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 81,
    "totalRevenue": 415.87,
    "totalOrders": 7,
    "avgRevenue": 5.13,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 81,
    "totalRevenue": 844,
    "totalOrders": 15,
    "avgRevenue": 10.42,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 81,
    "totalRevenue": 544.77,
    "totalOrders": 9,
    "avgRevenue": 6.73,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 81,
    "totalRevenue": 773.53,
    "totalOrders": 13,
    "avgRevenue": 9.55,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 81,
    "totalRevenue": 422.86,
    "totalOrders": 9,
    "avgRevenue": 5.22,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 81,
    "totalRevenue": 716.74,
    "totalOrders": 9,
    "avgRevenue": 8.85,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 81,
    "totalRevenue": 1209.63,
    "totalOrders": 21,
    "avgRevenue": 14.93,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 81,
    "totalRevenue": 1042.94,
    "totalOrders": 18,
    "avgRevenue": 12.88,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 81,
    "totalRevenue": 871.04,
    "totalOrders": 17,
    "avgRevenue": 10.75,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 81,
    "totalRevenue": 902.31,
    "totalOrders": 18,
    "avgRevenue": 11.14,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 81,
    "totalRevenue": 649.18,
    "totalOrders": 10,
    "avgRevenue": 8.01,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 81,
    "totalRevenue": 387.75,
    "totalOrders": 6,
    "avgRevenue": 4.79,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 76,
    "totalRevenue": 242.49,
    "totalOrders": 5,
    "avgRevenue": 3.19,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 76,
    "totalRevenue": 85.24,
    "totalOrders": 2,
    "avgRevenue": 1.12,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 76,
    "totalRevenue": 107.52,
    "totalOrders": 2,
    "avgRevenue": 1.41,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 76,
    "totalRevenue": 220.33,
    "totalOrders": 5,
    "avgRevenue": 2.9,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 76,
    "totalRevenue": 50.57,
    "totalOrders": 2,
    "avgRevenue": 0.67,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 76,
    "totalRevenue": 470.58,
    "totalOrders": 8,
    "avgRevenue": 6.19,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 76,
    "totalRevenue": 798.67,
    "totalOrders": 15,
    "avgRevenue": 10.51,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 76,
    "totalRevenue": 932.8,
    "totalOrders": 16,
    "avgRevenue": 12.27,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 76,
    "totalRevenue": 631.65,
    "totalOrders": 11,
    "avgRevenue": 8.31,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 76,
    "totalRevenue": 338.83,
    "totalOrders": 10,
    "avgRevenue": 4.46,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 76,
    "totalRevenue": 334.37,
    "totalOrders": 8,
    "avgRevenue": 4.4,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 76,
    "totalRevenue": 1237.91,
    "totalOrders": 21,
    "avgRevenue": 16.29,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 76,
    "totalRevenue": 678.62,
    "totalOrders": 11,
    "avgRevenue": 8.93,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 76,
    "totalRevenue": 749.72,
    "totalOrders": 15,
    "avgRevenue": 9.86,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 76,
    "totalRevenue": 860.21,
    "totalOrders": 21,
    "avgRevenue": 11.32,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 76,
    "totalRevenue": 662.25,
    "totalOrders": 13,
    "avgRevenue": 8.71,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 76,
    "totalRevenue": 921.34,
    "totalOrders": 13,
    "avgRevenue": 12.12,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 76,
    "totalRevenue": 1312.04,
    "totalOrders": 23,
    "avgRevenue": 17.26,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 76,
    "totalRevenue": 681.08,
    "totalOrders": 13,
    "avgRevenue": 8.96,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 76,
    "totalRevenue": 191.64,
    "totalOrders": 3,
    "avgRevenue": 2.52,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 80,
    "totalRevenue": 278.82,
    "totalOrders": 3,
    "avgRevenue": 3.49,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 80,
    "totalRevenue": 57.18,
    "totalOrders": 2,
    "avgRevenue": 0.71,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 80,
    "totalRevenue": 71.98,
    "totalOrders": 1,
    "avgRevenue": 0.9,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 80,
    "totalRevenue": 19.06,
    "totalOrders": 1,
    "avgRevenue": 0.24,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 80,
    "totalRevenue": 49.4,
    "totalOrders": 1,
    "avgRevenue": 0.62,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 80,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 80,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 80,
    "totalRevenue": 136.14,
    "totalOrders": 3,
    "avgRevenue": 1.7,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 80,
    "totalRevenue": 429.19,
    "totalOrders": 8,
    "avgRevenue": 5.36,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 80,
    "totalRevenue": 697.34,
    "totalOrders": 11,
    "avgRevenue": 8.72,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 80,
    "totalRevenue": 675.31,
    "totalOrders": 11,
    "avgRevenue": 8.44,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 80,
    "totalRevenue": 514.71,
    "totalOrders": 12,
    "avgRevenue": 6.43,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 80,
    "totalRevenue": 713.45,
    "totalOrders": 14,
    "avgRevenue": 8.92,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 80,
    "totalRevenue": 752.08,
    "totalOrders": 9,
    "avgRevenue": 9.4,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 80,
    "totalRevenue": 533.78,
    "totalOrders": 13,
    "avgRevenue": 6.67,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 80,
    "totalRevenue": 462.69,
    "totalOrders": 12,
    "avgRevenue": 5.78,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 80,
    "totalRevenue": 869.46,
    "totalOrders": 9,
    "avgRevenue": 10.87,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 80,
    "totalRevenue": 641.88,
    "totalOrders": 9,
    "avgRevenue": 8.02,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 80,
    "totalRevenue": 995.2,
    "totalOrders": 17,
    "avgRevenue": 12.44,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 80,
    "totalRevenue": 1053.06,
    "totalOrders": 19,
    "avgRevenue": 13.16,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 80,
    "totalRevenue": 635.69,
    "totalOrders": 12,
    "avgRevenue": 7.95,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 80,
    "totalRevenue": 853.83,
    "totalOrders": 16,
    "avgRevenue": 10.67,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 80,
    "totalRevenue": 915.38,
    "totalOrders": 13,
    "avgRevenue": 11.44,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 80,
    "totalRevenue": 35.02,
    "totalOrders": 2,
    "avgRevenue": 0.44,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 72,
    "totalRevenue": 138.43,
    "totalOrders": 3,
    "avgRevenue": 1.92,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 72,
    "totalRevenue": 34.76,
    "totalOrders": 1,
    "avgRevenue": 0.48,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 72,
    "totalRevenue": 122.19,
    "totalOrders": 3,
    "avgRevenue": 1.7,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 72,
    "totalRevenue": 78.45,
    "totalOrders": 2,
    "avgRevenue": 1.09,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 72,
    "totalRevenue": 297.37,
    "totalOrders": 7,
    "avgRevenue": 4.13,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 72,
    "totalRevenue": 340.66,
    "totalOrders": 7,
    "avgRevenue": 4.73,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 72,
    "totalRevenue": 528.46,
    "totalOrders": 12,
    "avgRevenue": 7.34,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 72,
    "totalRevenue": 437.07,
    "totalOrders": 10,
    "avgRevenue": 6.07,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 72,
    "totalRevenue": 429.27,
    "totalOrders": 11,
    "avgRevenue": 5.96,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 72,
    "totalRevenue": 357.16,
    "totalOrders": 8,
    "avgRevenue": 4.96,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 72,
    "totalRevenue": 351.75,
    "totalOrders": 9,
    "avgRevenue": 4.89,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 72,
    "totalRevenue": 74.22,
    "totalOrders": 2,
    "avgRevenue": 1.03,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 72,
    "totalRevenue": 372.96,
    "totalOrders": 5,
    "avgRevenue": 5.18,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 72,
    "totalRevenue": 532.02,
    "totalOrders": 9,
    "avgRevenue": 7.39,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 72,
    "totalRevenue": 773.72,
    "totalOrders": 9,
    "avgRevenue": 10.75,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 72,
    "totalRevenue": 542.8,
    "totalOrders": 10,
    "avgRevenue": 7.54,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 72,
    "totalRevenue": 867.87,
    "totalOrders": 19,
    "avgRevenue": 12.05,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 72,
    "totalRevenue": 574.51,
    "totalOrders": 10,
    "avgRevenue": 7.98,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 72,
    "totalRevenue": 495.84,
    "totalOrders": 10,
    "avgRevenue": 6.89,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 72,
    "totalRevenue": 331.5,
    "totalOrders": 8,
    "avgRevenue": 4.6,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 72,
    "totalRevenue": 544.26,
    "totalOrders": 8,
    "avgRevenue": 7.56,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 76,
    "totalRevenue": 76.37,
    "totalOrders": 2,
    "avgRevenue": 1,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 76,
    "totalRevenue": 50.26,
    "totalOrders": 2,
    "avgRevenue": 0.66,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 76,
    "totalRevenue": 77.82,
    "totalOrders": 2,
    "avgRevenue": 1.02,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 76,
    "totalRevenue": 25.44,
    "totalOrders": 1,
    "avgRevenue": 0.33,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 76,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 76,
    "totalRevenue": 26.41,
    "totalOrders": 1,
    "avgRevenue": 0.35,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 76,
    "totalRevenue": 193.14,
    "totalOrders": 3,
    "avgRevenue": 2.54,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 76,
    "totalRevenue": 134.41,
    "totalOrders": 2,
    "avgRevenue": 1.77,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 76,
    "totalRevenue": 105.97,
    "totalOrders": 2,
    "avgRevenue": 1.39,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 76,
    "totalRevenue": 427.14,
    "totalOrders": 10,
    "avgRevenue": 5.62,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 76,
    "totalRevenue": 783.49,
    "totalOrders": 15,
    "avgRevenue": 10.31,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 76,
    "totalRevenue": 844.99,
    "totalOrders": 12,
    "avgRevenue": 11.12,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 76,
    "totalRevenue": 942.4,
    "totalOrders": 9,
    "avgRevenue": 12.4,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 76,
    "totalRevenue": 357.14,
    "totalOrders": 8,
    "avgRevenue": 4.7,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 76,
    "totalRevenue": 577.27,
    "totalOrders": 10,
    "avgRevenue": 7.6,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 76,
    "totalRevenue": 358.93,
    "totalOrders": 7,
    "avgRevenue": 4.72,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 76,
    "totalRevenue": 358.96,
    "totalOrders": 6,
    "avgRevenue": 4.72,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 76,
    "totalRevenue": 315.97,
    "totalOrders": 6,
    "avgRevenue": 4.16,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 76,
    "totalRevenue": 673.36,
    "totalOrders": 12,
    "avgRevenue": 8.86,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 76,
    "totalRevenue": 401.48,
    "totalOrders": 9,
    "avgRevenue": 5.28,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 76,
    "totalRevenue": 655.05,
    "totalOrders": 12,
    "avgRevenue": 8.62,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 76,
    "totalRevenue": 680.01,
    "totalOrders": 14,
    "avgRevenue": 8.95,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 76,
    "totalRevenue": 273.51,
    "totalOrders": 4,
    "avgRevenue": 3.6,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 76,
    "totalRevenue": 494.41,
    "totalOrders": 5,
    "avgRevenue": 6.51,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 71,
    "totalRevenue": 88.07,
    "totalOrders": 1,
    "avgRevenue": 1.24,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 71,
    "totalRevenue": 70.92,
    "totalOrders": 1,
    "avgRevenue": 1,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 71,
    "totalRevenue": 68.93,
    "totalOrders": 1,
    "avgRevenue": 0.97,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 71,
    "totalRevenue": 409.85,
    "totalOrders": 7,
    "avgRevenue": 5.77,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 71,
    "totalRevenue": 220.36,
    "totalOrders": 5,
    "avgRevenue": 3.1,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 71,
    "totalRevenue": 915.92,
    "totalOrders": 14,
    "avgRevenue": 12.9,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 71,
    "totalRevenue": 521.47,
    "totalOrders": 9,
    "avgRevenue": 7.34,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 71,
    "totalRevenue": 304.44,
    "totalOrders": 7,
    "avgRevenue": 4.29,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 71,
    "totalRevenue": 273.49,
    "totalOrders": 10,
    "avgRevenue": 3.85,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 71,
    "totalRevenue": 553.62,
    "totalOrders": 10,
    "avgRevenue": 7.8,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 71,
    "totalRevenue": 388.37,
    "totalOrders": 6,
    "avgRevenue": 5.47,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 71,
    "totalRevenue": 371.26,
    "totalOrders": 8,
    "avgRevenue": 5.23,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 71,
    "totalRevenue": 768.84,
    "totalOrders": 9,
    "avgRevenue": 10.83,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 71,
    "totalRevenue": 545.89,
    "totalOrders": 9,
    "avgRevenue": 7.69,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 71,
    "totalRevenue": 568.09,
    "totalOrders": 10,
    "avgRevenue": 8,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 71,
    "totalRevenue": 331.27,
    "totalOrders": 6,
    "avgRevenue": 4.67,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 71,
    "totalRevenue": 254.32,
    "totalOrders": 8,
    "avgRevenue": 3.58,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 71,
    "totalRevenue": 419.71,
    "totalOrders": 11,
    "avgRevenue": 5.91,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 71,
    "totalRevenue": 291.4,
    "totalOrders": 5,
    "avgRevenue": 4.1,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 71,
    "totalRevenue": 516.72,
    "totalOrders": 8,
    "avgRevenue": 7.28,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 67,
    "totalRevenue": 145.7,
    "totalOrders": 3,
    "avgRevenue": 2.17,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 67,
    "totalRevenue": 119.61,
    "totalOrders": 1,
    "avgRevenue": 1.79,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 67,
    "totalRevenue": 68.78,
    "totalOrders": 1,
    "avgRevenue": 1.03,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 67,
    "totalRevenue": 58.88,
    "totalOrders": 2,
    "avgRevenue": 0.88,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 67,
    "totalRevenue": 550.42,
    "totalOrders": 8,
    "avgRevenue": 8.22,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 67,
    "totalRevenue": 338.65,
    "totalOrders": 7,
    "avgRevenue": 5.05,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 67,
    "totalRevenue": 473.4,
    "totalOrders": 8,
    "avgRevenue": 7.07,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 67,
    "totalRevenue": 652.35,
    "totalOrders": 10,
    "avgRevenue": 9.74,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 67,
    "totalRevenue": 545.43,
    "totalOrders": 11,
    "avgRevenue": 8.14,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 67,
    "totalRevenue": 432.77,
    "totalOrders": 7,
    "avgRevenue": 6.46,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 67,
    "totalRevenue": 197.64,
    "totalOrders": 4,
    "avgRevenue": 2.95,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 67,
    "totalRevenue": 231.62,
    "totalOrders": 6,
    "avgRevenue": 3.46,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 67,
    "totalRevenue": 296.11,
    "totalOrders": 6,
    "avgRevenue": 4.42,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 67,
    "totalRevenue": 450.8,
    "totalOrders": 10,
    "avgRevenue": 6.73,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 67,
    "totalRevenue": 751.13,
    "totalOrders": 11,
    "avgRevenue": 11.21,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 67,
    "totalRevenue": 247.55,
    "totalOrders": 8,
    "avgRevenue": 3.69,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 67,
    "totalRevenue": 433.59,
    "totalOrders": 6,
    "avgRevenue": 6.47,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 67,
    "totalRevenue": 630.49,
    "totalOrders": 10,
    "avgRevenue": 9.41,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 67,
    "totalRevenue": 248.32,
    "totalOrders": 6,
    "avgRevenue": 3.71,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 67,
    "totalRevenue": 556.56,
    "totalOrders": 9,
    "avgRevenue": 8.31,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 67,
    "totalRevenue": 152.49,
    "totalOrders": 4,
    "avgRevenue": 2.28,
    "avgOrders": 0.06
  }
];
