// Auto-generated by scripts/updateData.js — last update: 2026-03-30
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 40,
    "totalRevenue": 733.93,
    "totalOrders": 1,
    "avgRevenue": 18.35,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 40,
    "totalRevenue": 2053.57,
    "totalOrders": 2,
    "avgRevenue": 51.34,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 40,
    "totalRevenue": 4101.16,
    "totalOrders": 5,
    "avgRevenue": 102.53,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 40,
    "totalRevenue": 3441.14,
    "totalOrders": 3,
    "avgRevenue": 86.03,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 40,
    "totalRevenue": 11306.09,
    "totalOrders": 9,
    "avgRevenue": 282.65,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 40,
    "totalRevenue": 5476.49,
    "totalOrders": 7,
    "avgRevenue": 136.91,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 40,
    "totalRevenue": 11269.91,
    "totalOrders": 10,
    "avgRevenue": 281.75,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 40,
    "totalRevenue": 13344.2,
    "totalOrders": 13,
    "avgRevenue": 333.61,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 40,
    "totalRevenue": 18408.34,
    "totalOrders": 15,
    "avgRevenue": 460.21,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 40,
    "totalRevenue": 34030.29,
    "totalOrders": 15,
    "avgRevenue": 850.76,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 40,
    "totalRevenue": 9743.65,
    "totalOrders": 8,
    "avgRevenue": 243.59,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 40,
    "totalRevenue": 7631.33,
    "totalOrders": 10,
    "avgRevenue": 190.78,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 40,
    "totalRevenue": 11070.18,
    "totalOrders": 13,
    "avgRevenue": 276.75,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 40,
    "totalRevenue": 22951.27,
    "totalOrders": 15,
    "avgRevenue": 573.78,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 40,
    "totalRevenue": 21151.13,
    "totalOrders": 17,
    "avgRevenue": 528.78,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 40,
    "totalRevenue": 25439.95,
    "totalOrders": 16,
    "avgRevenue": 636,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 40,
    "totalRevenue": 9120.93,
    "totalOrders": 8,
    "avgRevenue": 228.02,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 40,
    "totalRevenue": 11750.53,
    "totalOrders": 8,
    "avgRevenue": 293.76,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 40,
    "totalRevenue": 9917.23,
    "totalOrders": 9,
    "avgRevenue": 247.93,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 40,
    "totalRevenue": 4386.62,
    "totalOrders": 2,
    "avgRevenue": 109.67,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 40,
    "totalRevenue": 1657.85,
    "totalOrders": 1,
    "avgRevenue": 41.45,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 40,
    "totalRevenue": 2005.36,
    "totalOrders": 1,
    "avgRevenue": 50.13,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 40,
    "totalRevenue": 993.75,
    "totalOrders": 1,
    "avgRevenue": 24.84,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 40,
    "totalRevenue": 1203.58,
    "totalOrders": 1,
    "avgRevenue": 30.09,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 40,
    "totalRevenue": 5258.93,
    "totalOrders": 3,
    "avgRevenue": 131.47,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 40,
    "totalRevenue": 2413.41,
    "totalOrders": 2,
    "avgRevenue": 60.34,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 40,
    "totalRevenue": 7060.12,
    "totalOrders": 5,
    "avgRevenue": 176.5,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 40,
    "totalRevenue": 3635.17,
    "totalOrders": 2,
    "avgRevenue": 90.88,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 40,
    "totalRevenue": 16397.79,
    "totalOrders": 14,
    "avgRevenue": 409.94,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 40,
    "totalRevenue": 9235.1,
    "totalOrders": 9,
    "avgRevenue": 230.88,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 40,
    "totalRevenue": 8618.97,
    "totalOrders": 7,
    "avgRevenue": 215.47,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 40,
    "totalRevenue": 10027.32,
    "totalOrders": 10,
    "avgRevenue": 250.68,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 40,
    "totalRevenue": 5394.66,
    "totalOrders": 6,
    "avgRevenue": 134.87,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 40,
    "totalRevenue": 12304.26,
    "totalOrders": 9,
    "avgRevenue": 307.61,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 40,
    "totalRevenue": 14085.97,
    "totalOrders": 13,
    "avgRevenue": 352.15,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 40,
    "totalRevenue": 12523.08,
    "totalOrders": 7,
    "avgRevenue": 313.08,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 40,
    "totalRevenue": 18732.34,
    "totalOrders": 16,
    "avgRevenue": 468.31,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 40,
    "totalRevenue": 28357.81,
    "totalOrders": 16,
    "avgRevenue": 708.95,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 40,
    "totalRevenue": 2735.74,
    "totalOrders": 4,
    "avgRevenue": 68.39,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 40,
    "totalRevenue": 31564.68,
    "totalOrders": 23,
    "avgRevenue": 789.12,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 40,
    "totalRevenue": 24233.83,
    "totalOrders": 17,
    "avgRevenue": 605.85,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 40,
    "totalRevenue": 4504.51,
    "totalOrders": 3,
    "avgRevenue": 112.61,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 39,
    "totalRevenue": 1563.29,
    "totalOrders": 2,
    "avgRevenue": 40.08,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 39,
    "totalRevenue": 3583.98,
    "totalOrders": 3,
    "avgRevenue": 91.9,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 39,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 39,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 39,
    "totalRevenue": 2810.72,
    "totalOrders": 2,
    "avgRevenue": 72.07,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 39,
    "totalRevenue": 1832.14,
    "totalOrders": 1,
    "avgRevenue": 46.98,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 39,
    "totalRevenue": 4955.25,
    "totalOrders": 5,
    "avgRevenue": 127.06,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 39,
    "totalRevenue": 5307.98,
    "totalOrders": 5,
    "avgRevenue": 136.1,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 39,
    "totalRevenue": 6150.79,
    "totalOrders": 6,
    "avgRevenue": 157.71,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 39,
    "totalRevenue": 13766.34,
    "totalOrders": 11,
    "avgRevenue": 352.98,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 39,
    "totalRevenue": 16955.88,
    "totalOrders": 12,
    "avgRevenue": 434.77,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 39,
    "totalRevenue": 23796.64,
    "totalOrders": 20,
    "avgRevenue": 610.17,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 39,
    "totalRevenue": 9697.12,
    "totalOrders": 9,
    "avgRevenue": 248.64,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 39,
    "totalRevenue": 12346.97,
    "totalOrders": 9,
    "avgRevenue": 316.59,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 39,
    "totalRevenue": 14989.46,
    "totalOrders": 11,
    "avgRevenue": 384.35,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 39,
    "totalRevenue": 12631.1,
    "totalOrders": 8,
    "avgRevenue": 323.87,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 39,
    "totalRevenue": 6904.74,
    "totalOrders": 4,
    "avgRevenue": 177.04,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 39,
    "totalRevenue": 11622.78,
    "totalOrders": 8,
    "avgRevenue": 298.02,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 39,
    "totalRevenue": 18079.25,
    "totalOrders": 12,
    "avgRevenue": 463.57,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 39,
    "totalRevenue": 22564.27,
    "totalOrders": 17,
    "avgRevenue": 578.57,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 39,
    "totalRevenue": 20391.64,
    "totalOrders": 19,
    "avgRevenue": 522.86,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 39,
    "totalRevenue": 20327.03,
    "totalOrders": 20,
    "avgRevenue": 521.21,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 39,
    "totalRevenue": 22027.07,
    "totalOrders": 20,
    "avgRevenue": 564.8,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 39,
    "totalRevenue": 13513.26,
    "totalOrders": 9,
    "avgRevenue": 346.49,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 40,
    "totalRevenue": 6149.83,
    "totalOrders": 6,
    "avgRevenue": 153.75,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 40,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 40,
    "totalRevenue": 1428.94,
    "totalOrders": 2,
    "avgRevenue": 35.72,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 40,
    "totalRevenue": 1029.47,
    "totalOrders": 1,
    "avgRevenue": 25.74,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 40,
    "totalRevenue": 1044.63,
    "totalOrders": 1,
    "avgRevenue": 26.12,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 40,
    "totalRevenue": 2121.42,
    "totalOrders": 1,
    "avgRevenue": 53.04,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 40,
    "totalRevenue": 2053.57,
    "totalOrders": 1,
    "avgRevenue": 51.34,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 40,
    "totalRevenue": 3600.24,
    "totalOrders": 4,
    "avgRevenue": 90.01,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 40,
    "totalRevenue": 9410.94,
    "totalOrders": 8,
    "avgRevenue": 235.27,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 40,
    "totalRevenue": 7680.21,
    "totalOrders": 7,
    "avgRevenue": 192.01,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 40,
    "totalRevenue": 11560.78,
    "totalOrders": 12,
    "avgRevenue": 289.02,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 40,
    "totalRevenue": 9926.63,
    "totalOrders": 7,
    "avgRevenue": 248.17,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 40,
    "totalRevenue": 10595.91,
    "totalOrders": 9,
    "avgRevenue": 264.9,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 40,
    "totalRevenue": 5719.75,
    "totalOrders": 6,
    "avgRevenue": 142.99,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 40,
    "totalRevenue": 9187.89,
    "totalOrders": 9,
    "avgRevenue": 229.7,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 40,
    "totalRevenue": 17122.31,
    "totalOrders": 8,
    "avgRevenue": 428.06,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 40,
    "totalRevenue": 11078.44,
    "totalOrders": 9,
    "avgRevenue": 276.96,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 40,
    "totalRevenue": 13712.81,
    "totalOrders": 9,
    "avgRevenue": 342.82,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 40,
    "totalRevenue": 5705.34,
    "totalOrders": 5,
    "avgRevenue": 142.63,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 40,
    "totalRevenue": 16843.79,
    "totalOrders": 12,
    "avgRevenue": 421.09,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 40,
    "totalRevenue": 19478.58,
    "totalOrders": 18,
    "avgRevenue": 486.96,
    "avgOrders": 0.45
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 40,
    "totalRevenue": 15130.44,
    "totalOrders": 13,
    "avgRevenue": 378.26,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 40,
    "totalRevenue": 12462.17,
    "totalOrders": 13,
    "avgRevenue": 311.55,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 40,
    "totalRevenue": 6175.59,
    "totalOrders": 7,
    "avgRevenue": 154.39,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 42,
    "totalRevenue": 6221.29,
    "totalOrders": 3,
    "avgRevenue": 148.13,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 42,
    "totalRevenue": 503.31,
    "totalOrders": 1,
    "avgRevenue": 11.98,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 42,
    "totalRevenue": 1683.94,
    "totalOrders": 2,
    "avgRevenue": 40.09,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 42,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 42,
    "totalRevenue": 1110.75,
    "totalOrders": 1,
    "avgRevenue": 26.45,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 42,
    "totalRevenue": 1884.82,
    "totalOrders": 1,
    "avgRevenue": 44.88,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 42,
    "totalRevenue": 4947.14,
    "totalOrders": 3,
    "avgRevenue": 117.79,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 42,
    "totalRevenue": 6673.79,
    "totalOrders": 5,
    "avgRevenue": 158.9,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 42,
    "totalRevenue": 7138.16,
    "totalOrders": 5,
    "avgRevenue": 169.96,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 42,
    "totalRevenue": 13024.12,
    "totalOrders": 9,
    "avgRevenue": 310.1,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 42,
    "totalRevenue": 12628.45,
    "totalOrders": 11,
    "avgRevenue": 300.68,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 42,
    "totalRevenue": 13500.03,
    "totalOrders": 12,
    "avgRevenue": 321.43,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 42,
    "totalRevenue": 9460.54,
    "totalOrders": 8,
    "avgRevenue": 225.25,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 42,
    "totalRevenue": 7924.53,
    "totalOrders": 5,
    "avgRevenue": 188.68,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 42,
    "totalRevenue": 17783.84,
    "totalOrders": 13,
    "avgRevenue": 423.42,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 42,
    "totalRevenue": 6290.35,
    "totalOrders": 7,
    "avgRevenue": 149.77,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 42,
    "totalRevenue": 9492.31,
    "totalOrders": 8,
    "avgRevenue": 226.01,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 42,
    "totalRevenue": 13439.71,
    "totalOrders": 12,
    "avgRevenue": 319.99,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 42,
    "totalRevenue": 10911.72,
    "totalOrders": 9,
    "avgRevenue": 259.8,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 42,
    "totalRevenue": 13406.77,
    "totalOrders": 11,
    "avgRevenue": 319.21,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 42,
    "totalRevenue": 10465.4,
    "totalOrders": 9,
    "avgRevenue": 249.18,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 42,
    "totalRevenue": 17033.92,
    "totalOrders": 15,
    "avgRevenue": 405.57,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 42,
    "totalRevenue": 3340.47,
    "totalOrders": 5,
    "avgRevenue": 79.54,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 42,
    "totalRevenue": 4693.3,
    "totalOrders": 4,
    "avgRevenue": 111.75,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 35,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 35,
    "totalRevenue": 2775.01,
    "totalOrders": 2,
    "avgRevenue": 79.29,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 35,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 35,
    "totalRevenue": 1004.48,
    "totalOrders": 1,
    "avgRevenue": 28.7,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 35,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 35,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 35,
    "totalRevenue": 4938.41,
    "totalOrders": 4,
    "avgRevenue": 141.1,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 35,
    "totalRevenue": 5135.37,
    "totalOrders": 4,
    "avgRevenue": 146.72,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 35,
    "totalRevenue": 7277.35,
    "totalOrders": 8,
    "avgRevenue": 207.92,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 35,
    "totalRevenue": 6055.17,
    "totalOrders": 7,
    "avgRevenue": 173,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 35,
    "totalRevenue": 12556.98,
    "totalOrders": 11,
    "avgRevenue": 358.77,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 35,
    "totalRevenue": 20128.23,
    "totalOrders": 11,
    "avgRevenue": 575.09,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 35,
    "totalRevenue": 7412.27,
    "totalOrders": 6,
    "avgRevenue": 211.78,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 35,
    "totalRevenue": 8301.96,
    "totalOrders": 9,
    "avgRevenue": 237.2,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 35,
    "totalRevenue": 7405.26,
    "totalOrders": 5,
    "avgRevenue": 211.58,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 35,
    "totalRevenue": 6941.03,
    "totalOrders": 7,
    "avgRevenue": 198.32,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 35,
    "totalRevenue": 4692.49,
    "totalOrders": 6,
    "avgRevenue": 134.07,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 35,
    "totalRevenue": 12081.32,
    "totalOrders": 9,
    "avgRevenue": 345.18,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 35,
    "totalRevenue": 10942.54,
    "totalOrders": 14,
    "avgRevenue": 312.64,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 35,
    "totalRevenue": 10045.77,
    "totalOrders": 8,
    "avgRevenue": 287.02,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 35,
    "totalRevenue": 7795.23,
    "totalOrders": 9,
    "avgRevenue": 222.72,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 35,
    "totalRevenue": 8762.17,
    "totalOrders": 7,
    "avgRevenue": 250.35,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 35,
    "totalRevenue": 7742.88,
    "totalOrders": 7,
    "avgRevenue": 221.23,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 35,
    "totalRevenue": 4834.02,
    "totalOrders": 5,
    "avgRevenue": 138.11,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 34,
    "totalRevenue": 2939.29,
    "totalOrders": 2,
    "avgRevenue": 86.45,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 34,
    "totalRevenue": 486.62,
    "totalOrders": 1,
    "avgRevenue": 14.31,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 34,
    "totalRevenue": 754.47,
    "totalOrders": 1,
    "avgRevenue": 22.19,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 34,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 60.27,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 34,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 34,
    "totalRevenue": 2513.41,
    "totalOrders": 3,
    "avgRevenue": 73.92,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 34,
    "totalRevenue": 1649.99,
    "totalOrders": 2,
    "avgRevenue": 48.53,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 34,
    "totalRevenue": 10471.49,
    "totalOrders": 5,
    "avgRevenue": 307.99,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 34,
    "totalRevenue": 3956.4,
    "totalOrders": 4,
    "avgRevenue": 116.36,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 34,
    "totalRevenue": 15870.44,
    "totalOrders": 10,
    "avgRevenue": 466.78,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 34,
    "totalRevenue": 7589.29,
    "totalOrders": 5,
    "avgRevenue": 223.21,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 34,
    "totalRevenue": 4154.93,
    "totalOrders": 5,
    "avgRevenue": 122.2,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 34,
    "totalRevenue": 16681.51,
    "totalOrders": 13,
    "avgRevenue": 490.63,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 34,
    "totalRevenue": 12342.57,
    "totalOrders": 10,
    "avgRevenue": 363.02,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 34,
    "totalRevenue": 7648.53,
    "totalOrders": 7,
    "avgRevenue": 224.96,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 34,
    "totalRevenue": 11871.25,
    "totalOrders": 7,
    "avgRevenue": 349.15,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 34,
    "totalRevenue": 5270.02,
    "totalOrders": 4,
    "avgRevenue": 155,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 34,
    "totalRevenue": 12635.97,
    "totalOrders": 12,
    "avgRevenue": 371.65,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 34,
    "totalRevenue": 8318.03,
    "totalOrders": 7,
    "avgRevenue": 244.65,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 34,
    "totalRevenue": 3038.43,
    "totalOrders": 3,
    "avgRevenue": 89.37,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 34,
    "totalRevenue": 15389.24,
    "totalOrders": 13,
    "avgRevenue": 452.62,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 34,
    "totalRevenue": 12407.82,
    "totalOrders": 9,
    "avgRevenue": 364.94,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 34,
    "totalRevenue": 5773.71,
    "totalOrders": 4,
    "avgRevenue": 169.81,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 34,
    "totalRevenue": 2774.87,
    "totalOrders": 2,
    "avgRevenue": 81.61,
    "avgOrders": 0.06
  }
];
