// Auto-generated by scripts/updateData.js — last update: 2026-09-16
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 89,
    "totalRevenue": 96.74,
    "totalOrders": 4,
    "avgRevenue": 1.09,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 89,
    "totalRevenue": 175.83,
    "totalOrders": 4,
    "avgRevenue": 1.98,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 89,
    "totalRevenue": 80.32,
    "totalOrders": 1,
    "avgRevenue": 0.9,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 89,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 89,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 89,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 89,
    "totalRevenue": 172.15,
    "totalOrders": 4,
    "avgRevenue": 1.93,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 89,
    "totalRevenue": 294.04,
    "totalOrders": 7,
    "avgRevenue": 3.3,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 89,
    "totalRevenue": 687.9,
    "totalOrders": 12,
    "avgRevenue": 7.73,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 89,
    "totalRevenue": 250.52,
    "totalOrders": 6,
    "avgRevenue": 2.81,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 89,
    "totalRevenue": 715.75,
    "totalOrders": 17,
    "avgRevenue": 8.04,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 89,
    "totalRevenue": 891.9,
    "totalOrders": 14,
    "avgRevenue": 10.02,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 89,
    "totalRevenue": 543.48,
    "totalOrders": 9,
    "avgRevenue": 6.11,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 89,
    "totalRevenue": 960.53,
    "totalOrders": 17,
    "avgRevenue": 10.79,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 89,
    "totalRevenue": 544.77,
    "totalOrders": 9,
    "avgRevenue": 6.12,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 89,
    "totalRevenue": 773.53,
    "totalOrders": 13,
    "avgRevenue": 8.69,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 89,
    "totalRevenue": 422.86,
    "totalOrders": 9,
    "avgRevenue": 4.75,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 89,
    "totalRevenue": 826.33,
    "totalOrders": 11,
    "avgRevenue": 9.28,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 89,
    "totalRevenue": 1358.49,
    "totalOrders": 25,
    "avgRevenue": 15.26,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 89,
    "totalRevenue": 1088.08,
    "totalOrders": 19,
    "avgRevenue": 12.23,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 89,
    "totalRevenue": 952.75,
    "totalOrders": 19,
    "avgRevenue": 10.71,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 89,
    "totalRevenue": 1122.57,
    "totalOrders": 22,
    "avgRevenue": 12.61,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 89,
    "totalRevenue": 692.96,
    "totalOrders": 11,
    "avgRevenue": 7.79,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 89,
    "totalRevenue": 387.75,
    "totalOrders": 6,
    "avgRevenue": 4.36,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 84,
    "totalRevenue": 242.49,
    "totalOrders": 5,
    "avgRevenue": 2.89,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 84,
    "totalRevenue": 85.24,
    "totalOrders": 2,
    "avgRevenue": 1.01,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 84,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 84,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 84,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 84,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 84,
    "totalRevenue": 107.52,
    "totalOrders": 2,
    "avgRevenue": 1.28,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 84,
    "totalRevenue": 316.64,
    "totalOrders": 7,
    "avgRevenue": 3.77,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 84,
    "totalRevenue": 77.2,
    "totalOrders": 3,
    "avgRevenue": 0.92,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 84,
    "totalRevenue": 693.39,
    "totalOrders": 13,
    "avgRevenue": 8.25,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 84,
    "totalRevenue": 908.64,
    "totalOrders": 17,
    "avgRevenue": 10.82,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 84,
    "totalRevenue": 1095.89,
    "totalOrders": 20,
    "avgRevenue": 13.05,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 84,
    "totalRevenue": 631.65,
    "totalOrders": 11,
    "avgRevenue": 7.52,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 84,
    "totalRevenue": 357.6,
    "totalOrders": 11,
    "avgRevenue": 4.26,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 84,
    "totalRevenue": 387.91,
    "totalOrders": 10,
    "avgRevenue": 4.62,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 84,
    "totalRevenue": 1322.53,
    "totalOrders": 24,
    "avgRevenue": 15.74,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 84,
    "totalRevenue": 766.34,
    "totalOrders": 12,
    "avgRevenue": 9.12,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 84,
    "totalRevenue": 857.07,
    "totalOrders": 16,
    "avgRevenue": 10.2,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 84,
    "totalRevenue": 1111.67,
    "totalOrders": 25,
    "avgRevenue": 13.23,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 84,
    "totalRevenue": 849.46,
    "totalOrders": 16,
    "avgRevenue": 10.11,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 84,
    "totalRevenue": 921.34,
    "totalOrders": 13,
    "avgRevenue": 10.97,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 84,
    "totalRevenue": 1368.11,
    "totalOrders": 26,
    "avgRevenue": 16.29,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 84,
    "totalRevenue": 681.08,
    "totalOrders": 13,
    "avgRevenue": 8.11,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 84,
    "totalRevenue": 361.5,
    "totalOrders": 5,
    "avgRevenue": 4.3,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 89,
    "totalRevenue": 278.82,
    "totalOrders": 3,
    "avgRevenue": 3.13,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 89,
    "totalRevenue": 57.18,
    "totalOrders": 2,
    "avgRevenue": 0.64,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 89,
    "totalRevenue": 71.98,
    "totalOrders": 1,
    "avgRevenue": 0.81,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 89,
    "totalRevenue": 19.06,
    "totalOrders": 1,
    "avgRevenue": 0.21,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 89,
    "totalRevenue": 49.4,
    "totalOrders": 1,
    "avgRevenue": 0.56,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 89,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 89,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 89,
    "totalRevenue": 200.4,
    "totalOrders": 4,
    "avgRevenue": 2.25,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 89,
    "totalRevenue": 486.67,
    "totalOrders": 10,
    "avgRevenue": 5.47,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 89,
    "totalRevenue": 724.11,
    "totalOrders": 12,
    "avgRevenue": 8.14,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 89,
    "totalRevenue": 1146.6,
    "totalOrders": 14,
    "avgRevenue": 12.88,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 89,
    "totalRevenue": 962.52,
    "totalOrders": 18,
    "avgRevenue": 10.81,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 89,
    "totalRevenue": 795.82,
    "totalOrders": 17,
    "avgRevenue": 8.94,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 89,
    "totalRevenue": 963.63,
    "totalOrders": 13,
    "avgRevenue": 10.83,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 89,
    "totalRevenue": 820.9,
    "totalOrders": 17,
    "avgRevenue": 9.22,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 89,
    "totalRevenue": 751.16,
    "totalOrders": 14,
    "avgRevenue": 8.44,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 89,
    "totalRevenue": 904.91,
    "totalOrders": 10,
    "avgRevenue": 10.17,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 89,
    "totalRevenue": 964.14,
    "totalOrders": 11,
    "avgRevenue": 10.83,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 89,
    "totalRevenue": 1021.89,
    "totalOrders": 18,
    "avgRevenue": 11.48,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 89,
    "totalRevenue": 1380.21,
    "totalOrders": 26,
    "avgRevenue": 15.51,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 89,
    "totalRevenue": 835.82,
    "totalOrders": 16,
    "avgRevenue": 9.39,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 89,
    "totalRevenue": 915.36,
    "totalOrders": 18,
    "avgRevenue": 10.28,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 89,
    "totalRevenue": 1242.27,
    "totalOrders": 16,
    "avgRevenue": 13.96,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 89,
    "totalRevenue": 174.61,
    "totalOrders": 5,
    "avgRevenue": 1.96,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 80,
    "totalRevenue": 138.43,
    "totalOrders": 3,
    "avgRevenue": 1.73,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 80,
    "totalRevenue": 34.76,
    "totalOrders": 1,
    "avgRevenue": 0.43,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 80,
    "totalRevenue": 33.32,
    "totalOrders": 1,
    "avgRevenue": 0.42,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 80,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 80,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 80,
    "totalRevenue": 122.19,
    "totalOrders": 3,
    "avgRevenue": 1.53,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 80,
    "totalRevenue": 78.45,
    "totalOrders": 2,
    "avgRevenue": 0.98,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 80,
    "totalRevenue": 324.14,
    "totalOrders": 8,
    "avgRevenue": 4.05,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 80,
    "totalRevenue": 340.66,
    "totalOrders": 7,
    "avgRevenue": 4.26,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 80,
    "totalRevenue": 698.78,
    "totalOrders": 14,
    "avgRevenue": 8.73,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 80,
    "totalRevenue": 562.1,
    "totalOrders": 13,
    "avgRevenue": 7.03,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 80,
    "totalRevenue": 633.72,
    "totalOrders": 14,
    "avgRevenue": 7.92,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 80,
    "totalRevenue": 467.62,
    "totalOrders": 10,
    "avgRevenue": 5.85,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 80,
    "totalRevenue": 520.5,
    "totalOrders": 12,
    "avgRevenue": 6.51,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 80,
    "totalRevenue": 260.45,
    "totalOrders": 5,
    "avgRevenue": 3.26,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 80,
    "totalRevenue": 441.66,
    "totalOrders": 6,
    "avgRevenue": 5.52,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 80,
    "totalRevenue": 532.02,
    "totalOrders": 9,
    "avgRevenue": 6.65,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 80,
    "totalRevenue": 850.66,
    "totalOrders": 11,
    "avgRevenue": 10.63,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 80,
    "totalRevenue": 542.8,
    "totalOrders": 10,
    "avgRevenue": 6.78,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 80,
    "totalRevenue": 867.87,
    "totalOrders": 19,
    "avgRevenue": 10.85,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 80,
    "totalRevenue": 755.98,
    "totalOrders": 14,
    "avgRevenue": 9.45,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 80,
    "totalRevenue": 566.14,
    "totalOrders": 13,
    "avgRevenue": 7.08,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 80,
    "totalRevenue": 351.01,
    "totalOrders": 9,
    "avgRevenue": 4.39,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 80,
    "totalRevenue": 582.78,
    "totalOrders": 9,
    "avgRevenue": 7.28,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 83,
    "totalRevenue": 76.37,
    "totalOrders": 2,
    "avgRevenue": 0.92,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 83,
    "totalRevenue": 50.26,
    "totalOrders": 2,
    "avgRevenue": 0.61,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 83,
    "totalRevenue": 77.82,
    "totalOrders": 2,
    "avgRevenue": 0.94,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 83,
    "totalRevenue": 25.44,
    "totalOrders": 1,
    "avgRevenue": 0.31,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 83,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 83,
    "totalRevenue": 26.41,
    "totalOrders": 1,
    "avgRevenue": 0.32,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 83,
    "totalRevenue": 193.14,
    "totalOrders": 3,
    "avgRevenue": 2.33,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 83,
    "totalRevenue": 134.41,
    "totalOrders": 2,
    "avgRevenue": 1.62,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 83,
    "totalRevenue": 249.47,
    "totalOrders": 4,
    "avgRevenue": 3.01,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 83,
    "totalRevenue": 552.76,
    "totalOrders": 13,
    "avgRevenue": 6.66,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 83,
    "totalRevenue": 783.49,
    "totalOrders": 15,
    "avgRevenue": 9.44,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 83,
    "totalRevenue": 1036.3,
    "totalOrders": 15,
    "avgRevenue": 12.49,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 83,
    "totalRevenue": 1064.84,
    "totalOrders": 11,
    "avgRevenue": 12.83,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 83,
    "totalRevenue": 357.14,
    "totalOrders": 8,
    "avgRevenue": 4.3,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 83,
    "totalRevenue": 685.56,
    "totalOrders": 12,
    "avgRevenue": 8.26,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 83,
    "totalRevenue": 358.93,
    "totalOrders": 7,
    "avgRevenue": 4.32,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 83,
    "totalRevenue": 433.88,
    "totalOrders": 9,
    "avgRevenue": 5.23,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 83,
    "totalRevenue": 345.97,
    "totalOrders": 7,
    "avgRevenue": 4.17,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 83,
    "totalRevenue": 766.94,
    "totalOrders": 16,
    "avgRevenue": 9.24,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 83,
    "totalRevenue": 574.89,
    "totalOrders": 13,
    "avgRevenue": 6.93,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 83,
    "totalRevenue": 655.05,
    "totalOrders": 12,
    "avgRevenue": 7.89,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 83,
    "totalRevenue": 680.01,
    "totalOrders": 14,
    "avgRevenue": 8.19,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 83,
    "totalRevenue": 372.32,
    "totalOrders": 5,
    "avgRevenue": 4.49,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 83,
    "totalRevenue": 494.41,
    "totalOrders": 5,
    "avgRevenue": 5.96,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 79,
    "totalRevenue": 107.57,
    "totalOrders": 2,
    "avgRevenue": 1.36,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 79,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 79,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 79,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 79,
    "totalRevenue": 70.92,
    "totalOrders": 1,
    "avgRevenue": 0.9,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 79,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 79,
    "totalRevenue": 106.21,
    "totalOrders": 2,
    "avgRevenue": 1.34,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 79,
    "totalRevenue": 452.93,
    "totalOrders": 8,
    "avgRevenue": 5.73,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 79,
    "totalRevenue": 247.13,
    "totalOrders": 6,
    "avgRevenue": 3.13,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 79,
    "totalRevenue": 933.77,
    "totalOrders": 15,
    "avgRevenue": 11.82,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 79,
    "totalRevenue": 816.25,
    "totalOrders": 13,
    "avgRevenue": 10.33,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 79,
    "totalRevenue": 304.44,
    "totalOrders": 7,
    "avgRevenue": 3.85,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 79,
    "totalRevenue": 373.64,
    "totalOrders": 12,
    "avgRevenue": 4.73,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 79,
    "totalRevenue": 820.42,
    "totalOrders": 12,
    "avgRevenue": 10.39,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 79,
    "totalRevenue": 476.39,
    "totalOrders": 8,
    "avgRevenue": 6.03,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 79,
    "totalRevenue": 396.34,
    "totalOrders": 9,
    "avgRevenue": 5.02,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 79,
    "totalRevenue": 869.21,
    "totalOrders": 11,
    "avgRevenue": 11,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 79,
    "totalRevenue": 662.39,
    "totalOrders": 11,
    "avgRevenue": 8.38,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 79,
    "totalRevenue": 699.37,
    "totalOrders": 12,
    "avgRevenue": 8.85,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 79,
    "totalRevenue": 470.48,
    "totalOrders": 8,
    "avgRevenue": 5.96,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 79,
    "totalRevenue": 266.22,
    "totalOrders": 9,
    "avgRevenue": 3.37,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 79,
    "totalRevenue": 480.15,
    "totalOrders": 12,
    "avgRevenue": 6.08,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 79,
    "totalRevenue": 397.95,
    "totalOrders": 8,
    "avgRevenue": 5.04,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 79,
    "totalRevenue": 516.72,
    "totalOrders": 8,
    "avgRevenue": 6.54,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 75,
    "totalRevenue": 170.41,
    "totalOrders": 4,
    "avgRevenue": 2.27,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 75,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 75,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 75,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 75,
    "totalRevenue": 119.61,
    "totalOrders": 1,
    "avgRevenue": 1.59,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 75,
    "totalRevenue": 68.78,
    "totalOrders": 1,
    "avgRevenue": 0.92,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 75,
    "totalRevenue": 58.88,
    "totalOrders": 2,
    "avgRevenue": 0.79,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 75,
    "totalRevenue": 636.43,
    "totalOrders": 9,
    "avgRevenue": 8.49,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 75,
    "totalRevenue": 417.68,
    "totalOrders": 8,
    "avgRevenue": 5.57,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 75,
    "totalRevenue": 473.4,
    "totalOrders": 8,
    "avgRevenue": 6.31,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 75,
    "totalRevenue": 893.43,
    "totalOrders": 17,
    "avgRevenue": 11.91,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 75,
    "totalRevenue": 762.75,
    "totalOrders": 14,
    "avgRevenue": 10.17,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 75,
    "totalRevenue": 597.19,
    "totalOrders": 10,
    "avgRevenue": 7.96,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 75,
    "totalRevenue": 197.64,
    "totalOrders": 4,
    "avgRevenue": 2.64,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 75,
    "totalRevenue": 231.62,
    "totalOrders": 6,
    "avgRevenue": 3.09,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 75,
    "totalRevenue": 479.06,
    "totalOrders": 9,
    "avgRevenue": 6.39,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 75,
    "totalRevenue": 670.79,
    "totalOrders": 13,
    "avgRevenue": 8.94,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 75,
    "totalRevenue": 1041.71,
    "totalOrders": 17,
    "avgRevenue": 13.89,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 75,
    "totalRevenue": 309.55,
    "totalOrders": 9,
    "avgRevenue": 4.13,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 75,
    "totalRevenue": 495.62,
    "totalOrders": 7,
    "avgRevenue": 6.61,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 75,
    "totalRevenue": 721.61,
    "totalOrders": 12,
    "avgRevenue": 9.62,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 75,
    "totalRevenue": 248.32,
    "totalOrders": 6,
    "avgRevenue": 3.31,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 75,
    "totalRevenue": 556.56,
    "totalOrders": 9,
    "avgRevenue": 7.42,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 75,
    "totalRevenue": 152.49,
    "totalOrders": 4,
    "avgRevenue": 2.03,
    "avgOrders": 0.05
  }
];
