// Auto-generated by scripts/updateData.js — last update: 2026-07-28
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 57,
    "totalRevenue": 466.97,
    "totalOrders": 1,
    "avgRevenue": 8.19,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 57,
    "totalRevenue": 733.93,
    "totalOrders": 1,
    "avgRevenue": 12.88,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 57,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 35.95,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 57,
    "totalRevenue": 839.29,
    "totalOrders": 1,
    "avgRevenue": 14.72,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 57,
    "totalRevenue": 908.93,
    "totalOrders": 1,
    "avgRevenue": 15.95,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 57,
    "totalRevenue": 3165.18,
    "totalOrders": 4,
    "avgRevenue": 55.53,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 57,
    "totalRevenue": 5193.13,
    "totalOrders": 7,
    "avgRevenue": 91.11,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 57,
    "totalRevenue": 7495.65,
    "totalOrders": 8,
    "avgRevenue": 131.5,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 57,
    "totalRevenue": 19854.41,
    "totalOrders": 16,
    "avgRevenue": 348.32,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 57,
    "totalRevenue": 17635.36,
    "totalOrders": 16,
    "avgRevenue": 309.39,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 57,
    "totalRevenue": 21190.48,
    "totalOrders": 18,
    "avgRevenue": 371.76,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 57,
    "totalRevenue": 21790.66,
    "totalOrders": 20,
    "avgRevenue": 382.29,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 57,
    "totalRevenue": 41892.28,
    "totalOrders": 31,
    "avgRevenue": 734.95,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 57,
    "totalRevenue": 38341.03,
    "totalOrders": 21,
    "avgRevenue": 672.65,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 57,
    "totalRevenue": 22340.12,
    "totalOrders": 19,
    "avgRevenue": 391.93,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 57,
    "totalRevenue": 18446.58,
    "totalOrders": 24,
    "avgRevenue": 323.62,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 57,
    "totalRevenue": 22843.44,
    "totalOrders": 24,
    "avgRevenue": 400.76,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 57,
    "totalRevenue": 47324.13,
    "totalOrders": 33,
    "avgRevenue": 830.25,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 57,
    "totalRevenue": 44998.06,
    "totalOrders": 33,
    "avgRevenue": 789.44,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 57,
    "totalRevenue": 33676.6,
    "totalOrders": 25,
    "avgRevenue": 590.82,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 57,
    "totalRevenue": 29323.63,
    "totalOrders": 24,
    "avgRevenue": 514.45,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 57,
    "totalRevenue": 32028.33,
    "totalOrders": 25,
    "avgRevenue": 561.9,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 57,
    "totalRevenue": 28443.12,
    "totalOrders": 22,
    "avgRevenue": 499,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 58,
    "totalRevenue": 8908.97,
    "totalOrders": 5,
    "avgRevenue": 153.6,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 58,
    "totalRevenue": 4152.51,
    "totalOrders": 3,
    "avgRevenue": 71.6,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 58,
    "totalRevenue": 1189.3,
    "totalOrders": 1,
    "avgRevenue": 20.51,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 58,
    "totalRevenue": 2005.36,
    "totalOrders": 1,
    "avgRevenue": 34.58,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 58,
    "totalRevenue": 993.75,
    "totalOrders": 1,
    "avgRevenue": 17.13,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 58,
    "totalRevenue": 1203.58,
    "totalOrders": 1,
    "avgRevenue": 20.75,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 58,
    "totalRevenue": 5562.5,
    "totalOrders": 4,
    "avgRevenue": 95.91,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 58,
    "totalRevenue": 9505.38,
    "totalOrders": 8,
    "avgRevenue": 163.89,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 58,
    "totalRevenue": 13644.53,
    "totalOrders": 10,
    "avgRevenue": 235.25,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 58,
    "totalRevenue": 14129.39,
    "totalOrders": 11,
    "avgRevenue": 243.61,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 58,
    "totalRevenue": 25943.35,
    "totalOrders": 24,
    "avgRevenue": 447.3,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 58,
    "totalRevenue": 15874.39,
    "totalOrders": 13,
    "avgRevenue": 273.7,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 58,
    "totalRevenue": 22518.11,
    "totalOrders": 19,
    "avgRevenue": 388.24,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 58,
    "totalRevenue": 20623.32,
    "totalOrders": 19,
    "avgRevenue": 355.57,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 58,
    "totalRevenue": 15947.55,
    "totalOrders": 16,
    "avgRevenue": 274.96,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 58,
    "totalRevenue": 27538.29,
    "totalOrders": 22,
    "avgRevenue": 474.8,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 58,
    "totalRevenue": 23779.79,
    "totalOrders": 23,
    "avgRevenue": 410,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 58,
    "totalRevenue": 19948.66,
    "totalOrders": 15,
    "avgRevenue": 343.94,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 58,
    "totalRevenue": 30100.24,
    "totalOrders": 23,
    "avgRevenue": 518.97,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 58,
    "totalRevenue": 44745.85,
    "totalOrders": 30,
    "avgRevenue": 771.48,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 58,
    "totalRevenue": 26719,
    "totalOrders": 22,
    "avgRevenue": 460.67,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 58,
    "totalRevenue": 39736.15,
    "totalOrders": 33,
    "avgRevenue": 685.11,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 58,
    "totalRevenue": 31329.29,
    "totalOrders": 24,
    "avgRevenue": 540.16,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 58,
    "totalRevenue": 22783.69,
    "totalOrders": 18,
    "avgRevenue": 392.82,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 57,
    "totalRevenue": 9090.1,
    "totalOrders": 9,
    "avgRevenue": 159.48,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 57,
    "totalRevenue": 7365.24,
    "totalOrders": 5,
    "avgRevenue": 129.21,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 57,
    "totalRevenue": 319.65,
    "totalOrders": 1,
    "avgRevenue": 5.61,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 57,
    "totalRevenue": 2810.72,
    "totalOrders": 2,
    "avgRevenue": 49.31,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 57,
    "totalRevenue": 3933.48,
    "totalOrders": 2,
    "avgRevenue": 69.01,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 57,
    "totalRevenue": 4955.25,
    "totalOrders": 5,
    "avgRevenue": 86.93,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 57,
    "totalRevenue": 8998.2,
    "totalOrders": 11,
    "avgRevenue": 157.86,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 57,
    "totalRevenue": 8707.07,
    "totalOrders": 10,
    "avgRevenue": 152.76,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 57,
    "totalRevenue": 21977.96,
    "totalOrders": 20,
    "avgRevenue": 385.58,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 57,
    "totalRevenue": 34296.16,
    "totalOrders": 26,
    "avgRevenue": 601.69,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 57,
    "totalRevenue": 37961.86,
    "totalOrders": 30,
    "avgRevenue": 666,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 57,
    "totalRevenue": 21170.83,
    "totalOrders": 18,
    "avgRevenue": 371.42,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 57,
    "totalRevenue": 25829.59,
    "totalOrders": 20,
    "avgRevenue": 453.15,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 57,
    "totalRevenue": 25287.32,
    "totalOrders": 21,
    "avgRevenue": 443.64,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 57,
    "totalRevenue": 19435.41,
    "totalOrders": 17,
    "avgRevenue": 340.97,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 57,
    "totalRevenue": 24241.41,
    "totalOrders": 18,
    "avgRevenue": 425.29,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 57,
    "totalRevenue": 23817.45,
    "totalOrders": 18,
    "avgRevenue": 417.85,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 57,
    "totalRevenue": 47877.08,
    "totalOrders": 27,
    "avgRevenue": 839.95,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 57,
    "totalRevenue": 36044.7,
    "totalOrders": 30,
    "avgRevenue": 632.36,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 57,
    "totalRevenue": 37020.94,
    "totalOrders": 28,
    "avgRevenue": 649.49,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 57,
    "totalRevenue": 33303.41,
    "totalOrders": 33,
    "avgRevenue": 584.27,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 57,
    "totalRevenue": 34176.27,
    "totalOrders": 29,
    "avgRevenue": 599.58,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 57,
    "totalRevenue": 26428.52,
    "totalOrders": 20,
    "avgRevenue": 463.66,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 57,
    "totalRevenue": 9698.04,
    "totalOrders": 9,
    "avgRevenue": 170.14,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 57,
    "totalRevenue": 3280.73,
    "totalOrders": 3,
    "avgRevenue": 57.56,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 57,
    "totalRevenue": 1029.47,
    "totalOrders": 1,
    "avgRevenue": 18.06,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 57,
    "totalRevenue": 1044.63,
    "totalOrders": 1,
    "avgRevenue": 18.33,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 57,
    "totalRevenue": 4366.97,
    "totalOrders": 3,
    "avgRevenue": 76.61,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 57,
    "totalRevenue": 2583.94,
    "totalOrders": 2,
    "avgRevenue": 45.33,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 57,
    "totalRevenue": 12666.76,
    "totalOrders": 9,
    "avgRevenue": 222.22,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 57,
    "totalRevenue": 19151.6,
    "totalOrders": 16,
    "avgRevenue": 335.99,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 57,
    "totalRevenue": 19008.38,
    "totalOrders": 15,
    "avgRevenue": 333.48,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 57,
    "totalRevenue": 26859.84,
    "totalOrders": 25,
    "avgRevenue": 471.23,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 57,
    "totalRevenue": 20374.88,
    "totalOrders": 18,
    "avgRevenue": 357.45,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 57,
    "totalRevenue": 17504.43,
    "totalOrders": 14,
    "avgRevenue": 307.1,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 57,
    "totalRevenue": 16175.13,
    "totalOrders": 13,
    "avgRevenue": 283.77,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 57,
    "totalRevenue": 20239.75,
    "totalOrders": 20,
    "avgRevenue": 355.08,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 57,
    "totalRevenue": 32120.11,
    "totalOrders": 22,
    "avgRevenue": 563.51,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 57,
    "totalRevenue": 24586.07,
    "totalOrders": 17,
    "avgRevenue": 431.33,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 57,
    "totalRevenue": 18259.27,
    "totalOrders": 14,
    "avgRevenue": 320.34,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 57,
    "totalRevenue": 23947.38,
    "totalOrders": 19,
    "avgRevenue": 420.13,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 57,
    "totalRevenue": 23928.66,
    "totalOrders": 17,
    "avgRevenue": 419.8,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 57,
    "totalRevenue": 24461.65,
    "totalOrders": 24,
    "avgRevenue": 429.15,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 57,
    "totalRevenue": 28451.91,
    "totalOrders": 21,
    "avgRevenue": 499.16,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 57,
    "totalRevenue": 24251.67,
    "totalOrders": 22,
    "avgRevenue": 425.47,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 57,
    "totalRevenue": 16365.37,
    "totalOrders": 15,
    "avgRevenue": 287.11,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 59,
    "totalRevenue": 8073.09,
    "totalOrders": 4,
    "avgRevenue": 136.83,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 59,
    "totalRevenue": 6173.87,
    "totalOrders": 2,
    "avgRevenue": 104.64,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 59,
    "totalRevenue": 5557.14,
    "totalOrders": 4,
    "avgRevenue": 94.19,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 59,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 59,
    "totalRevenue": 1970.58,
    "totalOrders": 2,
    "avgRevenue": 33.4,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 59,
    "totalRevenue": 4486.59,
    "totalOrders": 3,
    "avgRevenue": 76.04,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 59,
    "totalRevenue": 4947.14,
    "totalOrders": 3,
    "avgRevenue": 83.85,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 59,
    "totalRevenue": 9453.27,
    "totalOrders": 8,
    "avgRevenue": 160.22,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 59,
    "totalRevenue": 17265.84,
    "totalOrders": 9,
    "avgRevenue": 292.64,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 59,
    "totalRevenue": 18546.49,
    "totalOrders": 15,
    "avgRevenue": 314.35,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 59,
    "totalRevenue": 25867.8,
    "totalOrders": 24,
    "avgRevenue": 438.44,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 59,
    "totalRevenue": 29017.92,
    "totalOrders": 22,
    "avgRevenue": 491.83,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 59,
    "totalRevenue": 23815.48,
    "totalOrders": 18,
    "avgRevenue": 403.65,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 59,
    "totalRevenue": 20746.89,
    "totalOrders": 16,
    "avgRevenue": 351.64,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 59,
    "totalRevenue": 36396.4,
    "totalOrders": 27,
    "avgRevenue": 616.89,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 59,
    "totalRevenue": 18973.17,
    "totalOrders": 15,
    "avgRevenue": 321.58,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 59,
    "totalRevenue": 18298.63,
    "totalOrders": 16,
    "avgRevenue": 310.15,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 59,
    "totalRevenue": 16855.8,
    "totalOrders": 15,
    "avgRevenue": 285.69,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 59,
    "totalRevenue": 19424.7,
    "totalOrders": 17,
    "avgRevenue": 329.23,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 59,
    "totalRevenue": 30806.83,
    "totalOrders": 22,
    "avgRevenue": 522.15,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 59,
    "totalRevenue": 15196.65,
    "totalOrders": 14,
    "avgRevenue": 257.57,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 59,
    "totalRevenue": 28885.17,
    "totalOrders": 27,
    "avgRevenue": 489.58,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 59,
    "totalRevenue": 17942.76,
    "totalOrders": 17,
    "avgRevenue": 304.11,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 59,
    "totalRevenue": 12688.87,
    "totalOrders": 10,
    "avgRevenue": 215.07,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 52,
    "totalRevenue": 5553.77,
    "totalOrders": 5,
    "avgRevenue": 106.8,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 52,
    "totalRevenue": 3230.37,
    "totalOrders": 3,
    "avgRevenue": 62.12,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 52,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 52,
    "totalRevenue": 2792.87,
    "totalOrders": 2,
    "avgRevenue": 53.71,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 52,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 52,
    "totalRevenue": 743.3,
    "totalOrders": 1,
    "avgRevenue": 14.29,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 52,
    "totalRevenue": 5758.05,
    "totalOrders": 5,
    "avgRevenue": 110.73,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 52,
    "totalRevenue": 10766.69,
    "totalOrders": 9,
    "avgRevenue": 207.05,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 52,
    "totalRevenue": 16760.43,
    "totalOrders": 18,
    "avgRevenue": 322.32,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 52,
    "totalRevenue": 20311.46,
    "totalOrders": 20,
    "avgRevenue": 390.6,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 52,
    "totalRevenue": 25082.89,
    "totalOrders": 20,
    "avgRevenue": 482.36,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 52,
    "totalRevenue": 36477.4,
    "totalOrders": 23,
    "avgRevenue": 701.49,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 52,
    "totalRevenue": 25336.58,
    "totalOrders": 16,
    "avgRevenue": 487.24,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 52,
    "totalRevenue": 27556.86,
    "totalOrders": 23,
    "avgRevenue": 529.94,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 52,
    "totalRevenue": 13608.83,
    "totalOrders": 9,
    "avgRevenue": 261.71,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 52,
    "totalRevenue": 27850.44,
    "totalOrders": 20,
    "avgRevenue": 535.59,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 52,
    "totalRevenue": 19663.99,
    "totalOrders": 18,
    "avgRevenue": 378.15,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 52,
    "totalRevenue": 16586.69,
    "totalOrders": 15,
    "avgRevenue": 318.97,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 52,
    "totalRevenue": 25504.2,
    "totalOrders": 25,
    "avgRevenue": 490.47,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 52,
    "totalRevenue": 17572.15,
    "totalOrders": 16,
    "avgRevenue": 337.93,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 52,
    "totalRevenue": 14058.2,
    "totalOrders": 14,
    "avgRevenue": 270.35,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 52,
    "totalRevenue": 20885.85,
    "totalOrders": 18,
    "avgRevenue": 401.65,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 52,
    "totalRevenue": 12037.53,
    "totalOrders": 12,
    "avgRevenue": 231.49,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 52,
    "totalRevenue": 12196.54,
    "totalOrders": 10,
    "avgRevenue": 234.55,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 51,
    "totalRevenue": 9925.02,
    "totalOrders": 5,
    "avgRevenue": 194.61,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 51,
    "totalRevenue": 1500.03,
    "totalOrders": 2,
    "avgRevenue": 29.41,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 51,
    "totalRevenue": 754.47,
    "totalOrders": 1,
    "avgRevenue": 14.79,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 51,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 40.18,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 51,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 51,
    "totalRevenue": 4500.03,
    "totalOrders": 4,
    "avgRevenue": 88.24,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 51,
    "totalRevenue": 8398.23,
    "totalOrders": 7,
    "avgRevenue": 164.67,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 51,
    "totalRevenue": 19818.84,
    "totalOrders": 7,
    "avgRevenue": 388.6,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 51,
    "totalRevenue": 12310.88,
    "totalOrders": 11,
    "avgRevenue": 241.39,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 51,
    "totalRevenue": 28509.77,
    "totalOrders": 20,
    "avgRevenue": 559.02,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 51,
    "totalRevenue": 18890.22,
    "totalOrders": 16,
    "avgRevenue": 370.4,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 51,
    "totalRevenue": 12298.73,
    "totalOrders": 15,
    "avgRevenue": 241.15,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 51,
    "totalRevenue": 27612.82,
    "totalOrders": 28,
    "avgRevenue": 541.43,
    "avgOrders": 0.55
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 51,
    "totalRevenue": 29140.01,
    "totalOrders": 21,
    "avgRevenue": 571.37,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 51,
    "totalRevenue": 18963.72,
    "totalOrders": 16,
    "avgRevenue": 371.84,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 51,
    "totalRevenue": 25581.09,
    "totalOrders": 15,
    "avgRevenue": 501.59,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 51,
    "totalRevenue": 12681.66,
    "totalOrders": 10,
    "avgRevenue": 248.66,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 51,
    "totalRevenue": 21815.44,
    "totalOrders": 19,
    "avgRevenue": 427.75,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 51,
    "totalRevenue": 19044.84,
    "totalOrders": 15,
    "avgRevenue": 373.43,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 51,
    "totalRevenue": 15218.4,
    "totalOrders": 11,
    "avgRevenue": 298.4,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 51,
    "totalRevenue": 33335.74,
    "totalOrders": 26,
    "avgRevenue": 653.64,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 51,
    "totalRevenue": 22784.18,
    "totalOrders": 19,
    "avgRevenue": 446.75,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 51,
    "totalRevenue": 15765.72,
    "totalOrders": 11,
    "avgRevenue": 309.13,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 51,
    "totalRevenue": 11872.71,
    "totalOrders": 8,
    "avgRevenue": 232.8,
    "avgOrders": 0.16
  }
];
