// Auto-generated by scripts/updateData.js — last update: 2026-08-25
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 61,
    "totalRevenue": 683.04,
    "totalOrders": 1,
    "avgRevenue": 11.2,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 61,
    "totalRevenue": 466.97,
    "totalOrders": 1,
    "avgRevenue": 7.66,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 61,
    "totalRevenue": 733.93,
    "totalOrders": 1,
    "avgRevenue": 12.03,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 61,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 33.59,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 61,
    "totalRevenue": 839.29,
    "totalOrders": 1,
    "avgRevenue": 13.76,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 61,
    "totalRevenue": 908.93,
    "totalOrders": 1,
    "avgRevenue": 14.9,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 61,
    "totalRevenue": 3165.18,
    "totalOrders": 4,
    "avgRevenue": 51.89,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 61,
    "totalRevenue": 5193.13,
    "totalOrders": 7,
    "avgRevenue": 85.13,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 61,
    "totalRevenue": 10962.61,
    "totalOrders": 11,
    "avgRevenue": 179.71,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 61,
    "totalRevenue": 22836.59,
    "totalOrders": 18,
    "avgRevenue": 374.37,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 61,
    "totalRevenue": 19519.3,
    "totalOrders": 17,
    "avgRevenue": 319.99,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 61,
    "totalRevenue": 22978,
    "totalOrders": 19,
    "avgRevenue": 376.69,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 61,
    "totalRevenue": 28929.08,
    "totalOrders": 28,
    "avgRevenue": 474.25,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 61,
    "totalRevenue": 52035.17,
    "totalOrders": 35,
    "avgRevenue": 853.04,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 61,
    "totalRevenue": 38341.03,
    "totalOrders": 21,
    "avgRevenue": 628.54,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 61,
    "totalRevenue": 23047.26,
    "totalOrders": 20,
    "avgRevenue": 377.82,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 61,
    "totalRevenue": 23037.57,
    "totalOrders": 27,
    "avgRevenue": 377.67,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 61,
    "totalRevenue": 31820.25,
    "totalOrders": 27,
    "avgRevenue": 521.64,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 61,
    "totalRevenue": 52675.39,
    "totalOrders": 37,
    "avgRevenue": 863.53,
    "avgOrders": 0.61
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 61,
    "totalRevenue": 45958.77,
    "totalOrders": 34,
    "avgRevenue": 753.42,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 61,
    "totalRevenue": 37825.92,
    "totalOrders": 28,
    "avgRevenue": 620.1,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 61,
    "totalRevenue": 34995.51,
    "totalOrders": 27,
    "avgRevenue": 573.7,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 61,
    "totalRevenue": 34034.58,
    "totalOrders": 28,
    "avgRevenue": 557.94,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 61,
    "totalRevenue": 29938.66,
    "totalOrders": 25,
    "avgRevenue": 490.8,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 62,
    "totalRevenue": 11850.05,
    "totalOrders": 8,
    "avgRevenue": 191.13,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 62,
    "totalRevenue": 6840.01,
    "totalOrders": 4,
    "avgRevenue": 110.32,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 62,
    "totalRevenue": 1189.3,
    "totalOrders": 1,
    "avgRevenue": 19.18,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 62,
    "totalRevenue": 2005.36,
    "totalOrders": 1,
    "avgRevenue": 32.34,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 62,
    "totalRevenue": 993.75,
    "totalOrders": 1,
    "avgRevenue": 16.03,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 62,
    "totalRevenue": 1203.58,
    "totalOrders": 1,
    "avgRevenue": 19.41,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 62,
    "totalRevenue": 5562.5,
    "totalOrders": 4,
    "avgRevenue": 89.72,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 62,
    "totalRevenue": 11742.9,
    "totalOrders": 9,
    "avgRevenue": 189.4,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 62,
    "totalRevenue": 14995.43,
    "totalOrders": 11,
    "avgRevenue": 241.86,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 62,
    "totalRevenue": 18039.22,
    "totalOrders": 15,
    "avgRevenue": 290.96,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 62,
    "totalRevenue": 29201.4,
    "totalOrders": 27,
    "avgRevenue": 470.99,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 62,
    "totalRevenue": 18736.02,
    "totalOrders": 17,
    "avgRevenue": 302.19,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 62,
    "totalRevenue": 26245.09,
    "totalOrders": 21,
    "avgRevenue": 423.31,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 62,
    "totalRevenue": 25606.37,
    "totalOrders": 23,
    "avgRevenue": 413.01,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 62,
    "totalRevenue": 15947.55,
    "totalOrders": 16,
    "avgRevenue": 257.22,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 62,
    "totalRevenue": 31767.77,
    "totalOrders": 25,
    "avgRevenue": 512.38,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 62,
    "totalRevenue": 26652.56,
    "totalOrders": 25,
    "avgRevenue": 429.88,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 62,
    "totalRevenue": 23980.82,
    "totalOrders": 20,
    "avgRevenue": 386.79,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 62,
    "totalRevenue": 33044.89,
    "totalOrders": 25,
    "avgRevenue": 532.98,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 62,
    "totalRevenue": 54988.3,
    "totalOrders": 35,
    "avgRevenue": 886.91,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 62,
    "totalRevenue": 30514.58,
    "totalOrders": 26,
    "avgRevenue": 492.17,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 62,
    "totalRevenue": 49087.07,
    "totalOrders": 40,
    "avgRevenue": 791.73,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 62,
    "totalRevenue": 39907.33,
    "totalOrders": 29,
    "avgRevenue": 643.67,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 62,
    "totalRevenue": 22783.69,
    "totalOrders": 18,
    "avgRevenue": 367.48,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 61,
    "totalRevenue": 13255.38,
    "totalOrders": 12,
    "avgRevenue": 217.3,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 61,
    "totalRevenue": 7365.24,
    "totalOrders": 5,
    "avgRevenue": 120.74,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 61,
    "totalRevenue": 1974.12,
    "totalOrders": 3,
    "avgRevenue": 32.36,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 61,
    "totalRevenue": 349.11,
    "totalOrders": 1,
    "avgRevenue": 5.72,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 61,
    "totalRevenue": 2810.72,
    "totalOrders": 2,
    "avgRevenue": 46.08,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 61,
    "totalRevenue": 3933.48,
    "totalOrders": 2,
    "avgRevenue": 64.48,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 61,
    "totalRevenue": 6763.29,
    "totalOrders": 6,
    "avgRevenue": 110.87,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 61,
    "totalRevenue": 9579.45,
    "totalOrders": 12,
    "avgRevenue": 157.04,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 61,
    "totalRevenue": 8707.07,
    "totalOrders": 10,
    "avgRevenue": 142.74,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 61,
    "totalRevenue": 22709.22,
    "totalOrders": 21,
    "avgRevenue": 372.28,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 61,
    "totalRevenue": 41429.2,
    "totalOrders": 32,
    "avgRevenue": 679.17,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 61,
    "totalRevenue": 42535.08,
    "totalOrders": 33,
    "avgRevenue": 697.3,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 61,
    "totalRevenue": 21777.08,
    "totalOrders": 19,
    "avgRevenue": 357,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 61,
    "totalRevenue": 28986.75,
    "totalOrders": 23,
    "avgRevenue": 475.19,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 61,
    "totalRevenue": 30360.56,
    "totalOrders": 25,
    "avgRevenue": 497.71,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 61,
    "totalRevenue": 20883.64,
    "totalOrders": 19,
    "avgRevenue": 342.35,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 61,
    "totalRevenue": 25148.57,
    "totalOrders": 20,
    "avgRevenue": 412.27,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 61,
    "totalRevenue": 25668.35,
    "totalOrders": 20,
    "avgRevenue": 420.79,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 61,
    "totalRevenue": 50004.77,
    "totalOrders": 29,
    "avgRevenue": 819.75,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 61,
    "totalRevenue": 39737.57,
    "totalOrders": 34,
    "avgRevenue": 651.44,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 61,
    "totalRevenue": 41952.57,
    "totalOrders": 33,
    "avgRevenue": 687.75,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 61,
    "totalRevenue": 39447.34,
    "totalOrders": 38,
    "avgRevenue": 646.68,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 61,
    "totalRevenue": 37906.66,
    "totalOrders": 32,
    "avgRevenue": 621.42,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 61,
    "totalRevenue": 31420.5,
    "totalOrders": 24,
    "avgRevenue": 515.09,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 61,
    "totalRevenue": 9698.04,
    "totalOrders": 9,
    "avgRevenue": 158.98,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 61,
    "totalRevenue": 664.3,
    "totalOrders": 1,
    "avgRevenue": 10.89,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 61,
    "totalRevenue": 3280.73,
    "totalOrders": 3,
    "avgRevenue": 53.78,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 61,
    "totalRevenue": 1029.47,
    "totalOrders": 1,
    "avgRevenue": 16.88,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 61,
    "totalRevenue": 1044.63,
    "totalOrders": 1,
    "avgRevenue": 17.13,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 61,
    "totalRevenue": 5168.76,
    "totalOrders": 4,
    "avgRevenue": 84.73,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 61,
    "totalRevenue": 2583.94,
    "totalOrders": 2,
    "avgRevenue": 42.36,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 61,
    "totalRevenue": 12666.76,
    "totalOrders": 9,
    "avgRevenue": 207.65,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 61,
    "totalRevenue": 19151.6,
    "totalOrders": 16,
    "avgRevenue": 313.96,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 61,
    "totalRevenue": 20992.31,
    "totalOrders": 17,
    "avgRevenue": 344.14,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 61,
    "totalRevenue": 29568.8,
    "totalOrders": 29,
    "avgRevenue": 484.73,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 61,
    "totalRevenue": 25482.97,
    "totalOrders": 22,
    "avgRevenue": 417.75,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 61,
    "totalRevenue": 17504.43,
    "totalOrders": 14,
    "avgRevenue": 286.96,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 61,
    "totalRevenue": 16961.74,
    "totalOrders": 14,
    "avgRevenue": 278.06,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 61,
    "totalRevenue": 25800.89,
    "totalOrders": 23,
    "avgRevenue": 422.97,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 61,
    "totalRevenue": 36626.39,
    "totalOrders": 26,
    "avgRevenue": 600.43,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 61,
    "totalRevenue": 28925.36,
    "totalOrders": 21,
    "avgRevenue": 474.19,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 61,
    "totalRevenue": 22781.61,
    "totalOrders": 17,
    "avgRevenue": 373.47,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 61,
    "totalRevenue": 25749.17,
    "totalOrders": 20,
    "avgRevenue": 422.12,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 61,
    "totalRevenue": 28271.55,
    "totalOrders": 20,
    "avgRevenue": 463.47,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 61,
    "totalRevenue": 26106.31,
    "totalOrders": 26,
    "avgRevenue": 427.97,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 61,
    "totalRevenue": 34235,
    "totalOrders": 25,
    "avgRevenue": 561.23,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 61,
    "totalRevenue": 28216.87,
    "totalOrders": 25,
    "avgRevenue": 462.57,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 61,
    "totalRevenue": 18458.7,
    "totalOrders": 17,
    "avgRevenue": 302.6,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 63,
    "totalRevenue": 9575.77,
    "totalOrders": 6,
    "avgRevenue": 152,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 63,
    "totalRevenue": 13314.51,
    "totalOrders": 4,
    "avgRevenue": 211.34,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 63,
    "totalRevenue": 5557.14,
    "totalOrders": 4,
    "avgRevenue": 88.21,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 63,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 63,
    "totalRevenue": 1970.58,
    "totalOrders": 2,
    "avgRevenue": 31.28,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 63,
    "totalRevenue": 4486.59,
    "totalOrders": 3,
    "avgRevenue": 71.22,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 63,
    "totalRevenue": 4947.14,
    "totalOrders": 3,
    "avgRevenue": 78.53,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 63,
    "totalRevenue": 11399.52,
    "totalOrders": 9,
    "avgRevenue": 180.94,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 63,
    "totalRevenue": 19114.95,
    "totalOrders": 11,
    "avgRevenue": 303.41,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 63,
    "totalRevenue": 21342.05,
    "totalOrders": 17,
    "avgRevenue": 338.76,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 63,
    "totalRevenue": 27818.7,
    "totalOrders": 27,
    "avgRevenue": 441.57,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 63,
    "totalRevenue": 34573.31,
    "totalOrders": 28,
    "avgRevenue": 548.78,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 63,
    "totalRevenue": 26620.85,
    "totalOrders": 21,
    "avgRevenue": 422.55,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 63,
    "totalRevenue": 22846.01,
    "totalOrders": 19,
    "avgRevenue": 362.64,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 63,
    "totalRevenue": 37058.9,
    "totalOrders": 28,
    "avgRevenue": 588.24,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 63,
    "totalRevenue": 22847.27,
    "totalOrders": 17,
    "avgRevenue": 362.66,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 63,
    "totalRevenue": 19054.88,
    "totalOrders": 17,
    "avgRevenue": 302.46,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 63,
    "totalRevenue": 18259.37,
    "totalOrders": 17,
    "avgRevenue": 289.83,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 63,
    "totalRevenue": 20542.57,
    "totalOrders": 18,
    "avgRevenue": 326.07,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 63,
    "totalRevenue": 31580.94,
    "totalOrders": 23,
    "avgRevenue": 501.28,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 63,
    "totalRevenue": 15679.69,
    "totalOrders": 15,
    "avgRevenue": 248.88,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 63,
    "totalRevenue": 33917.31,
    "totalOrders": 31,
    "avgRevenue": 538.37,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 63,
    "totalRevenue": 19372.22,
    "totalOrders": 18,
    "avgRevenue": 307.5,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 63,
    "totalRevenue": 15294.24,
    "totalOrders": 12,
    "avgRevenue": 242.77,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 56,
    "totalRevenue": 5553.77,
    "totalOrders": 5,
    "avgRevenue": 99.17,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 56,
    "totalRevenue": 3230.37,
    "totalOrders": 3,
    "avgRevenue": 57.69,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 56,
    "totalRevenue": 2792.87,
    "totalOrders": 2,
    "avgRevenue": 49.87,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 56,
    "totalRevenue": 2727.24,
    "totalOrders": 2,
    "avgRevenue": 48.7,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 56,
    "totalRevenue": 7033.05,
    "totalOrders": 7,
    "avgRevenue": 125.59,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 56,
    "totalRevenue": 11262.23,
    "totalOrders": 10,
    "avgRevenue": 201.11,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 56,
    "totalRevenue": 16760.43,
    "totalOrders": 18,
    "avgRevenue": 299.29,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 56,
    "totalRevenue": 22248.07,
    "totalOrders": 22,
    "avgRevenue": 397.29,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 56,
    "totalRevenue": 28649.87,
    "totalOrders": 22,
    "avgRevenue": 511.6,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 56,
    "totalRevenue": 39133.65,
    "totalOrders": 24,
    "avgRevenue": 698.82,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 56,
    "totalRevenue": 44468.02,
    "totalOrders": 20,
    "avgRevenue": 794.07,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 56,
    "totalRevenue": 29823.83,
    "totalOrders": 25,
    "avgRevenue": 532.57,
    "avgOrders": 0.45
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 56,
    "totalRevenue": 17360.64,
    "totalOrders": 13,
    "avgRevenue": 310.01,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 56,
    "totalRevenue": 32434.39,
    "totalOrders": 24,
    "avgRevenue": 579.19,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 56,
    "totalRevenue": 24828.28,
    "totalOrders": 22,
    "avgRevenue": 443.36,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 56,
    "totalRevenue": 21245.64,
    "totalOrders": 18,
    "avgRevenue": 379.39,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 56,
    "totalRevenue": 29635.45,
    "totalOrders": 29,
    "avgRevenue": 529.2,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 56,
    "totalRevenue": 19300.73,
    "totalOrders": 18,
    "avgRevenue": 344.66,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 56,
    "totalRevenue": 16553.76,
    "totalOrders": 18,
    "avgRevenue": 295.6,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 56,
    "totalRevenue": 24167.27,
    "totalOrders": 20,
    "avgRevenue": 431.56,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 56,
    "totalRevenue": 13276.81,
    "totalOrders": 13,
    "avgRevenue": 237.09,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 56,
    "totalRevenue": 16284.5,
    "totalOrders": 13,
    "avgRevenue": 290.79,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 55,
    "totalRevenue": 9925.02,
    "totalOrders": 5,
    "avgRevenue": 180.45,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 55,
    "totalRevenue": 2359.86,
    "totalOrders": 3,
    "avgRevenue": 42.91,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 55,
    "totalRevenue": 1482.15,
    "totalOrders": 2,
    "avgRevenue": 26.95,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 55,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 37.26,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 55,
    "totalRevenue": 4500.03,
    "totalOrders": 4,
    "avgRevenue": 81.82,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 55,
    "totalRevenue": 8398.23,
    "totalOrders": 7,
    "avgRevenue": 152.7,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 55,
    "totalRevenue": 21114.38,
    "totalOrders": 8,
    "avgRevenue": 383.9,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 55,
    "totalRevenue": 12766.24,
    "totalOrders": 12,
    "avgRevenue": 232.11,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 55,
    "totalRevenue": 29242.81,
    "totalOrders": 21,
    "avgRevenue": 531.69,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 55,
    "totalRevenue": 28825.77,
    "totalOrders": 24,
    "avgRevenue": 524.1,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 55,
    "totalRevenue": 13872.84,
    "totalOrders": 17,
    "avgRevenue": 252.23,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 55,
    "totalRevenue": 29537.82,
    "totalOrders": 30,
    "avgRevenue": 537.05,
    "avgOrders": 0.55
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 55,
    "totalRevenue": 32808.78,
    "totalOrders": 24,
    "avgRevenue": 596.52,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 55,
    "totalRevenue": 18963.72,
    "totalOrders": 16,
    "avgRevenue": 344.79,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 55,
    "totalRevenue": 26942.71,
    "totalOrders": 17,
    "avgRevenue": 489.87,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 55,
    "totalRevenue": 19744.2,
    "totalOrders": 14,
    "avgRevenue": 358.99,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 55,
    "totalRevenue": 25650.27,
    "totalOrders": 24,
    "avgRevenue": 466.37,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 55,
    "totalRevenue": 21047.54,
    "totalOrders": 18,
    "avgRevenue": 382.68,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 55,
    "totalRevenue": 17923.78,
    "totalOrders": 14,
    "avgRevenue": 325.89,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 55,
    "totalRevenue": 35114.33,
    "totalOrders": 28,
    "avgRevenue": 638.44,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 55,
    "totalRevenue": 23183.28,
    "totalOrders": 20,
    "avgRevenue": 421.51,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 55,
    "totalRevenue": 15765.72,
    "totalOrders": 11,
    "avgRevenue": 286.65,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 55,
    "totalRevenue": 13921.82,
    "totalOrders": 9,
    "avgRevenue": 253.12,
    "avgOrders": 0.16
  }
];
