// Auto-generated by scripts/updateData.js — last update: 2026-03-19
// CZ: per-customer retention data (CZK)

export const retentionDataCZ: { dates: string[]; revenues: number[]; revsVat: number[] }[] = [
  {
    "dates": [
      "2025-06-03"
    ],
    "revenues": [
      1084.3
    ],
    "revsVat": [
      1312
    ]
  },
  {
    "dates": [
      "2025-06-19"
    ],
    "revenues": [
      1393.39
    ],
    "revsVat": [
      1686
    ]
  },
  {
    "dates": [
      "2025-06-23"
    ],
    "revenues": [
      2405.38
    ],
    "revsVat": [
      2910.5
    ]
  },
  {
    "dates": [
      "2025-07-09"
    ],
    "revenues": [
      725.63
    ],
    "revsVat": [
      878
    ]
  },
  {
    "dates": [
      "2025-08-09"
    ],
    "revenues": [
      2284.3
    ],
    "revsVat": [
      2764
    ]
  },
  {
    "dates": [
      "2025-08-25"
    ],
    "revenues": [
      1733.88
    ],
    "revsVat": [
      2098
    ]
  },
  {
    "dates": [
      "2025-09-02"
    ],
    "revenues": [
      1159.51
    ],
    "revsVat": [
      1403
    ]
  },
  {
    "dates": [
      "2025-09-05"
    ],
    "revenues": [
      1330.58
    ],
    "revsVat": [
      1610
    ]
  },
  {
    "dates": [
      "2025-10-08"
    ],
    "revenues": [
      1503.31
    ],
    "revsVat": [
      1819
    ]
  },
  {
    "dates": [
      "2025-10-15"
    ],
    "revenues": [
      750.83
    ],
    "revsVat": [
      908.5
    ]
  },
  {
    "dates": [
      "2025-11-02"
    ],
    "revenues": [
      3312.39
    ],
    "revsVat": [
      4008
    ]
  },
  {
    "dates": [
      "2025-11-03"
    ],
    "revenues": [
      1852.07
    ],
    "revsVat": [
      2241
    ]
  },
  {
    "dates": [
      "2025-11-05"
    ],
    "revenues": [
      2339.68
    ],
    "revsVat": [
      2831
    ]
  },
  {
    "dates": [
      "2025-11-13"
    ],
    "revenues": [
      708.27
    ],
    "revsVat": [
      857
    ]
  },
  {
    "dates": [
      "2025-11-14",
      "2026-02-10"
    ],
    "revenues": [
      1695.05,
      2092.85
    ],
    "revsVat": [
      2051,
      2344
    ]
  },
  {
    "dates": [
      "2025-11-19",
      "2025-11-21"
    ],
    "revenues": [
      9225.86,
      9035.71
    ],
    "revsVat": [
      10332.97,
      10120
    ]
  },
  {
    "dates": [
      "2025-11-22"
    ],
    "revenues": [
      1786.61
    ],
    "revsVat": [
      2001
    ]
  },
  {
    "dates": [
      "2025-11-28"
    ],
    "revenues": [
      3037.5
    ],
    "revsVat": [
      3402
    ]
  },
  {
    "dates": [
      "2025-12-01"
    ],
    "revenues": [
      2538.41
    ],
    "revsVat": [
      2843
    ]
  },
  {
    "dates": [
      "2025-12-11",
      "2026-02-10"
    ],
    "revenues": [
      2724.1,
      3661.61
    ],
    "revsVat": [
      3051,
      4101
    ]
  },
  {
    "dates": [
      "2026-01-20"
    ],
    "revenues": [
      3469.67
    ],
    "revsVat": [
      3886
    ]
  },
  {
    "dates": [
      "2026-01-22"
    ],
    "revenues": [
      769.65
    ],
    "revsVat": [
      862
    ]
  },
  {
    "dates": [
      "2026-01-24"
    ],
    "revenues": [
      2084.82
    ],
    "revsVat": [
      2335
    ]
  },
  {
    "dates": [
      "2026-02-07",
      "2026-03-10"
    ],
    "revenues": [
      1912.5,
      2732.14
    ],
    "revsVat": [
      2142,
      3060
    ]
  },
  {
    "dates": [
      "2026-02-09"
    ],
    "revenues": [
      1679.47
    ],
    "revsVat": [
      1881
    ]
  },
  {
    "dates": [
      "2026-02-16"
    ],
    "revenues": [
      1153.57
    ],
    "revsVat": [
      1292
    ]
  },
  {
    "dates": [
      "2026-03-08"
    ],
    "revenues": [
      1619.64
    ],
    "revsVat": [
      1814
    ]
  },
  {
    "dates": [
      "2026-03-10"
    ],
    "revenues": [
      2084.28
    ],
    "revsVat": [
      2334.4
    ]
  },
  {
    "dates": [
      "2026-03-16"
    ],
    "revenues": [
      1305.35
    ],
    "revsVat": [
      1462
    ]
  }
];
