// Auto-generated by scripts/updateData.js — last update: 2026-03-19
// SK: per-customer retention data (EUR)

export const retentionDataSK: { dates: string[]; revenues: number[]; revsVat: number[] }[] = [
  {
    "dates": [
      "2024-06-14"
    ],
    "revenues": [
      50.06
    ],
    "revsVat": [
      60.06
    ]
  },
  {
    "dates": [
      "2024-06-15"
    ],
    "revenues": [
      43.47
    ],
    "revsVat": [
      52.17
    ]
  },
  {
    "dates": [
      "2024-07-19"
    ],
    "revenues": [
      71.26
    ],
    "revsVat": [
      85.51
    ]
  },
  {
    "dates": [
      "2024-10-05"
    ],
    "revenues": [
      37.43
    ],
    "revsVat": [
      44.91
    ]
  },
  {
    "dates": [
      "2024-10-12"
    ],
    "revenues": [
      67.83
    ],
    "revsVat": [
      81.4
    ]
  },
  {
    "dates": [
      "2024-10-18"
    ],
    "revenues": [
      49.5
    ],
    "revsVat": [
      59.39
    ]
  },
  {
    "dates": [
      "2024-11-19",
      "2026-02-15"
    ],
    "revenues": [
      21.13,
      115.39
    ],
    "revsVat": [
      25.35,
      137.31
    ]
  },
  {
    "dates": [
      "2025-02-15"
    ],
    "revenues": [
      185.08
    ],
    "revsVat": [
      220.27
    ]
  },
  {
    "dates": [
      "2025-02-19",
      "2025-07-24"
    ],
    "revenues": [
      101.65,
      211.48
    ],
    "revsVat": [
      120.96,
      251.67
    ]
  },
  {
    "dates": [
      "2025-05-30"
    ],
    "revenues": [
      34.14
    ],
    "revsVat": [
      40.62
    ]
  },
  {
    "dates": [
      "2025-08-21"
    ],
    "revenues": [
      190.08
    ],
    "revsVat": [
      226.2
    ]
  },
  {
    "dates": [
      "2025-11-05"
    ],
    "revenues": [
      71.1
    ],
    "revsVat": [
      84.62
    ]
  },
  {
    "dates": [
      "2025-11-13"
    ],
    "revenues": [
      27.7
    ],
    "revsVat": [
      32.96
    ]
  },
  {
    "dates": [
      "2025-11-28"
    ],
    "revenues": [
      78.91
    ],
    "revsVat": [
      93.9
    ]
  },
  {
    "dates": [
      "2025-12-16"
    ],
    "revenues": [
      42.9
    ],
    "revsVat": [
      51.05
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      120.71
    ],
    "revsVat": [
      143.65
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      165.09
    ],
    "revsVat": [
      196.48
    ]
  },
  {
    "dates": [
      "2026-01-18"
    ],
    "revenues": [
      47.77
    ],
    "revsVat": [
      56.84
    ]
  },
  {
    "dates": [
      "2026-02-03"
    ],
    "revenues": [
      72.38
    ],
    "revsVat": [
      86.14
    ]
  },
  {
    "dates": [
      "2026-02-04"
    ],
    "revenues": [
      41.56
    ],
    "revsVat": [
      49.46
    ]
  },
  {
    "dates": [
      "2026-02-22"
    ],
    "revenues": [
      75.56
    ],
    "revsVat": [
      89.92
    ]
  },
  {
    "dates": [
      "2026-03-15"
    ],
    "revenues": [
      67.39
    ],
    "revsVat": [
      80.19
    ]
  }
];
